### ISSUE TITLE
XCode 8, 1.6.8 Duplicate symbol issue

### ISSUE THREAD

**Issue by ngoctr** [paypal/paypal-here-sdk-ios-distribution#105]
We can't use PPH 1.6.8 as we got duplicate symbol issues Switched back to 1.6.6, no issue.
`clang: warning: libstdc++ is deprecated; move to libc++
duplicate symbol __ZN22SW_DecodeMagController11GetWavStateEv in:   <ProjectFolder>//Pods/PayPalHereSDK/SDK/Debug/PayPalHereSDK.framework/PayPalHereSDK(SW_DecodeMagController.o)
duplicate symbol __ZN22SW_DecodeMagControllerD1Ev in:
 <ProjectFolder>//Pods/PayPalHereSDK/SDK/Debug/PayPalHereSDK.framework/PayPalHereSDK(SW_DecodeMagController.o)
duplicate symbol __ZN22SW_DecodeMagControllerC1Ev in:
 <ProjectFolder>//Pods/PayPalHereSDK/SDK/Debug/PayPalHereSDK.framework/PayPalHereSDK(SW_DecodeMagController.o)
duplicate symbol __ZN22SW_DecodeMagController15SetTimeoutLimitEi in:
 <ProjectFolder>//Pods/PayPalHereSDK/SDK/Debug/PayPalHereSDK.framework/PayPalHereSDK(SW_DecodeMagController.o)
duplicate symbol __ZN22SW_DecodeMagController12InputDbLevelEd in:`

**Comment by ppmtscory** [comment]
Are you using Magtek libraries within your App as well?  Essentially it seems like you're using a third party library that's already included in the PPH SDK which is causing the duplicate.  The most common is when folks use reader/swiper libraries on their own which are also included in the SDK.
