### ISSUE TITLE
Active Merchant Crash 

### ISSUE THREAD

**Issue by dvalenzuela** [paypal/paypal-here-sdk-ios-distribution#111]
Using the method on PayPalHereSDK

+(void)setupWithCredentials:(NSString *)access_token refreshUrl:(NSString *)refresh_url tokenExpiryOrNil:(NSString *)expiry thenCompletionHandler:(PPHInitializationCompletionHandler) completionHandler;

Returns 
Status = ePPHAccessResultSuccess
error = nil
info = active merchant with currency code and all sets

When processing a check or cash payment I get the following crash
[PayPalHereSDK activeMerchant].currencyCode is nil. Either set this value or use initWithCurrency:

I've checked the singleton variable [PayPalHereSDK activeMerchant] and its returning nil.

Im able to reproduce this on latest SDK with iOS 10, 9 on both iPhone and iPad platforms.

**Comment by ppmtscory** [comment]
@dvalenzuela I spoke with Matthew this morning via skype regarding this and so I'm going to close this out for now.  If the issue reoccurs, please let us know.
