### ISSUE TITLE
Unable to include paypalhere SDK to podspec of a pod module

### ISSUE THREAD

**Issue by EddieLukeAtmey** [paypal/paypal-here-sdk-ios-distribution#113]
Hi guys, 

My co-worker and I are writing a dependent, reusable module, which supposes to work with PaypalHereSDK (and many other payment gateways). We expect it to become a local pod repository, which we'll use in our company's other project.

Problem is, we can't include your SDK pod to our podspec:

```
    s.dependency 'PaypalHereSDK'
```

Error: [!] Unable to find a specification for `PaypalHereSDK` depended upon by "myModule"

So, do you guys have any suggestion about using pod inside podspec? Other frameworks work just fine (E.g. AFNetworking, iZettleSDK...). Currently, we have to manually download and include pph framework, but with that, we won't have notice when new versions come out.

**Comment by ppmtscory** [comment]
It looks like you may have a capitalization issue with the pod name.  It should be capital P's in the name such as `PayPalHereSDK`, whereas you have it as `PaypalHereSDK`.  This link [here](https://github.com/CocoaPods/CocoaPods/issues/3877) outlines some issues folks were seeing with capitalization of dependencies.  Let me know if this works or not.
