### ISSUE TITLE
Xcode 8 warning libstdc++ is deprecated; move to libc++

### ISSUE THREAD

**Issue by dvalenzuela** [paypal/paypal-here-sdk-ios-distribution#114]
On Xcode 8.2.1 Apple is marking as a warning
 **libstdc++ to be deprecated.** 

If we update as per request from apple to libc++ on the build configuration we get Linker Errors like 
Undefined symbols for architecture arm64
"std::ios_base::Init::Init()", referenced from:
      __GLOBAL__sub_I_SW_FskController.mm in PayPalHereSDK(SW_FskController.o)

**Comment by ppmtscory** [comment]
Please utilize our newest SDK that's been released.
