### ISSUE TITLE
App integrated with 1.6.8 SDK was rejected by Apple

### ISSUE THREAD

**Issue by jinpengduan** [paypal/paypal-here-sdk-ios-distribution#115]
Hi,

Our POS app have PayPal Here integrated and after we swap in 1.6.8 SDK, our submission of updated app to Apple Store was rejected with this explanation:

"
1 package(s) were not uploaded because they had problems:
    /var/folders/rz/f9y16h6j0_39m5f1qrxprhg93xs7r4/T/DC116B91-2E9B-4347-9CB2-7405AF92B6B9/1001297342.itmsp - Error Messages:
        ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/ShowAndSell.app/PayPalHereSDK.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
"

We suspect this might have something to do with the value of CFBundleSupportedPlatforms in PayPalHereSDK.bundle/info.plist. In the Debug folder it's iPhoneOS whereas in the Release folder it's iPhoneSimulator. Can you help clarify if there's some tweak needed so we can get the app re-submitted and approved by Apple?

**Comment by ppmtscory** [comment]
Hello, @jinpengduan, yes this is incorrectly labeled in the Release version of the Info.plist file.  To submit your app, you can simply manually edit this to be the same as Debug (iPhoneOS) and it should be allowed.  We'll be changing this with the next release, but until then, you can manually edit it prior to submitting to Apple.
