### ISSUE TITLE
How long should I expect to get response from PPH-SDK

### ISSUE THREAD

**Issue by rleiwang** [paypal/paypal-here-sdk-ios-distribution#116]
Hi,

I have submitted the form to PPH-SDK. Does any one know how long should I expect to hear back?

Thanks,

**Comment by ppmtscory** [comment]
@rleiwang I see that your form was submitted earlier this week so you should hear something back either today or Monday most likely.

**Comment by rleiwang** [comment]
@ppmtscory I still haven't heard any thing yet. Could you help to check?

**Comment by ppmtscory** [comment]
I will shoot an email off and see if there's any update.  I'll have them update you via email.
