### ISSUE TITLE
Fetching detailed error info for any occured error

### ISSUE THREAD

**Issue by damavik** [paypal/paypal-here-sdk-ios-distribution#117]
Hi guys,

Probably I've misunderstood something but what's the production-ready method for fetching detailed error info? For instance where could I grab NSError/NSString for the ePPHTransactionType_FailedToReadCard transaction manager event?

And yes I've seen (and using) the following debug interface https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/SDK/Release/PayPalHereSDK.framework/Versions/A/Headers/PPHLoggingDelegate.h

But the problem is that it delivers raw (PayPal) internal debug messages, so seems like it's a monkey job to parse them on our side.

So what's the best practice?

Thanks

**Comment by ppmtscory** [comment]
Error handling within our new SDK that's been released has included improvements.  The error object received from a transaction should be sufficient, but please do let us know if you're seeing any messages that aren't clear.
