### ISSUE TITLE
PayPalHereSDK/Release App Store Submission Issue

### ISSUE THREAD

**Issue by sanjitsaluja** [paypal/paypal-here-sdk-ios-distribution#119]
`ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Chedda.app/PayPalHereSDK.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."`

**Comment by ppmtscory** [comment]
Hey @sanjitsaluja - you will need to adjust this value manually, in the Info.plist file, to iphoneos prior to submitting.  We'll try to fix this with our next release.

**Comment by sanjitsaluja** [comment]
Thank you @ppmtscory Do you which files?
