### ISSUE TITLE
SDK setup fails on iOS 10.x

### ISSUE THREAD

**Issue by damavik** [paypal/paypal-here-sdk-ios-distribution#124]
Has anybody noted that PPH SDK (version 1.6.8) just stopped working on iOS 10.x (e.g. with base SDK 10.3)? I mean the following error on +(void)setupWithCompositeTokenString:.. or +(void)setActiveMerchant:.. invocation:

> Error Domain=NSURLErrorDomain Code=-1005 The network connection was lost. apiMessage=(null) message=(null) correlationId=(null)

On iOS 9.x everything works correctly, SDK setup succeeds.

Haven't digged too deeply but looks like it's a **blocking issue**. It could be easily reproduced even with **TakePayment** sample from the SDK.

Any thoughts on that?

**Comment by ppmtscory** [comment]
I just ran the TakePayment app on Friday to gather some logs and everything worked fine.  I was using 10.2.1.  Also, I ran another app, using the PPH SDK with the iPad on 10.3.1 and that also connected fine.  Can you post a ticket to www.paypal-techsupport.com/app/ask and provide the account email addresses that you are using?  I don't want you posting that info here in a public forum.  Let me know the ticket number here once it's generated and I'll be sure to have somebody take a look.

**Comment by damavik** [comment]
@ppmtscory Well there's no secret. I just tried the **TakePayment** sample within sandbox env. For that I changed the login url to [http://pph-retail-sdk-sample.herokuapp.com/toPayPal/sandbox](http://pph-retail-sdk-sample.herokuapp.com/toPayPal/sandbox) and used a sandbox acc **test-biz-1-us@pp.com** (got from [http://pp-retail.com/sdk/](http://pp-retail.com/sdk/)). The actual result is failed **PayPalHereSDK::setupWithCompositeTokenString:...** request with the following error:

NSURLErrorDomain Code=-1005 "The network connection was lost.", i.e. init result is **ePPHInitResultFailed**

Running environment -  xCode 8.3 and iPad Mini 4 with the Firmware 10.3.1

Actual logger output - https://gist.github.com/damavik/bcf8c46261d3e18e1ad8384ef8e44de0

Just to emphasize - everything works ok on an iPad with the Firmware 9.3.5

**Comment by ppmtscory** [comment]
I'll run it with that account and see if I can reproduce.

**Comment by ppmtscory** [comment]
@damavik it appears that there's an issue with the /status endpoint that's used in the Sandbox.  I will have the team take a look right away.  Thanks for reporting.

**Comment by ppmtscory** [comment]
@damavik it looks like there's something different with the way things are handled with 10.3.  I use a 10.2 simulator and everything works fine, but when I switch to 10.3, I see the same crash.  I'll continue to dig and see what we need to update in the sample app.

**Comment by damavik** [comment]
@ppmtscory Sorry for disturbing.
Any news on that issue? What's an ETA for the fix?

**Comment by ppmtscory** [comment]
I haven't found a resolution just yet, but I can tell you that it only happens on sandbox and only for 10.3.  Therefore, for your testing, please continue to use 10.2 for the sandbox environment.

**Comment by ppmtscory** [comment]
Our newest SDK is now available and should solve any lingering issues regarding this particular issue.
