### ISSUE TITLE
Invalid CFBundleSupportedPlatformsValue 

### ISSUE THREAD

**Issue by jnwagstaff** [paypal/paypal-here-sdk-ios-distribution#130]
![screen shot 2017-06-15 at 10 22 20 am](https://user-images.githubusercontent.com/19917310/27191354-c476a346-51b4-11e7-95a3-1112b8d6b500.png)

When I try to push this to testflight this is the error I get.  Is there any way we can remove this key from the info plist?

**Comment by ppmtscory** [comment]
You simply need to change it to `iphoneos` instead of `iphonesimulator`.  We'll fix it if there's another push but I don't anticipate that as we're getting ready to release the 2.0 version of the SDK.

**Comment by jnwagstaff** [comment]
Okay sounds great thanks for the response
