### ISSUE TITLE
Unregistered Account

### ISSUE THREAD

**Issue by jnwagstaff** [paypal/paypal-here-sdk-ios-distribution#133]
I have not been able to find a way to see if the active merchant is registered with PPH.  I get a token back if the user has a paypal account but not registered with Pay Pal Here.  I've read a lot of the docs and haven't found anything that tells me if they are registered or not.

**Comment by ppmtscory** [comment]
Check out the _Status Check_ section of [this page](https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding/initiating-the-onboarding-flow/).
