### ISSUE TITLE
Error on refund 

### ISSUE THREAD

**Issue by thwaiteschris** [paypal/paypal-here-sdk-ios-distribution#134]
I am trying to give a refund on a successful PayPal Here transaction. I have the TransactionId, but no other information.
My code is as follows:

```
NSString* str = transactionId;
PPHTransactionRecord* record = [[PPHTransactionRecord alloc] initWithTransactionId:str];
[[PayPalHereSDK sharedTransactionManager] beginRefund:record forAmount:nil completionHandler: ^(PPHTransactionResponse *response){
     if(response.error){
        // do stuff
    } else{
        // do other stuff
    }
}];
```

However, this always comes back with the error:

> processing a refund is not allowed in this state

When I look at the transaction in question in my PayPal dashboard, I cannot see anything unusual about it. The status is "Completed" and in the transaction detail page I have the option (which works) to "issue a refund".

Is there any way to find out exactly why I am unable to process the refund via the PayPal Here api?

The examples in the SDK all show issueing a refund from the invoice, which I do not have access to. All I have (without a major re-write to my app) is the orignal transaction Id, which is why I'm trying to do it this way.

**Comment by thwaiteschris** [comment]
OK, so I've found a work-around for this. Instead of processing the refund through the sharedTransactionManager (which always errors), I can process it through the sharedPaymentProcessor:

```
NSString* str = transactionId;
[[PayPalHereSDK sharedPaymentProcessor] beginRefund:str forAmount:nil completionHandler:^(PPHPaymentResponse *response) {
                if(response.error){
                    NSString *jsScript = @"ferry.payment.creditCardRefundFailure();";
                    [_theWebView evaluateJavaScript:jsScript completionHandler:^(id result, NSError * error) {}];
                } else{
                    NSString *jsScript = [NSString stringWithFormat:@"ferry.payment.creditCardRefundSuccess('%@');", str];
                    [_theWebView evaluateJavaScript:jsScript completionHandler:^(id result, NSError * error) {}];
                }
            }];
```

I'll leave the issue open, since I feel like the original issue of an error when using the sharedTransactionManager still stands. But feel free to close it if you wish.

Cheers,
   Chris

**Comment by ppmtscory** [comment]
Can you please share the transaction ID that you're trying to refund?

**Comment by thwaiteschris** [comment]
Sure, it's 7PY09357FG981493A

Please let me know if there's any other info that would be useful.

**Comment by ppmtscory** [comment]
Hmm... I don't see anything with that transaction, and I was able to successfully init a transaction record and do a refund.  Below is the code I used (Swift):
```
let txnRec = PPHTransactionRecord.init(transactionId: "5CA99010056170921")
        
PayPalHereSDK.sharedTransactionManager().beginRefund(txnRec, for: nil, completionHandler: ({( response ) -> Void in
            if((response?.error) != nil) {
                print("Error: \(response?.error)")
            } else {
                print("Begin Refund success: \(response)")
            }
}))
```

**Comment by thwaiteschris** [comment]
OK... since it all seems to be working as expected for you I'm happy to assume there's something weird in my implementation and close the issue. 

Like I said, I found a work-around, so only left the issue open for your info.

Thanks for looking into it.
