### ISSUE TITLE
Active Merchant not Persisting

### ISSUE THREAD

**Issue by jnwagstaff** [paypal/paypal-here-sdk-ios-distribution#136]
So in the docs it mentions that the active merchant info will persist in secure storage.  Every time I restart the app the activemerchant is now nil?  Do I need to save the compositeString in userdefaults to keep refreshing the active merchant every time after they open the app or the active merchant is nil?

**Comment by ppmtscory** [comment]
You can use UserDefaults if you like, for testing, but I wouldn't recommend that for a production scenario.  Essentially, each time the customer logs into your app, you would grab the appropriate token, from your server, to pass into the SDK.  Each time they login, you'd run the `setupWithCredentials` or `setupWithCompositeTokenString`, whichever you're using.

**Comment by jnwagstaff** [comment]
Would you recommend storing the refresh token securely in keychain access and grabbing the access token using that refresh?

**Comment by ppmtscory** [comment]
Any refresh tokens should be stored server side.  Your refresh URL should point to your server that will then get the appropriate refresh token and generate a new access token to then pass back into the SDK.

**Comment by jnwagstaff** [comment]
So basically a user would have to login to pay pal here every time they open the app after quitting unless we tie our PPH tokens to our users in our system?

**Comment by ppmtscory** [comment]
Yes, that's correct.  You'll want to store the refresh token for each user so that you can generate an access token for them automatically and they don't have to go through the login each time.
