### ISSUE TITLE
Any update on the next release?

### ISSUE THREAD

**Issue by ngoctr** [paypal/paypal-here-sdk-ios-distribution#140]
It has been almost a year since the last release, is there any update on a better PPH v2?

**Comment by ppmtscory** [comment]
We're hoping to have something ready by the end of the year, otherwise early on in Q1.  Is there a specific feature or something unavailable that's deterring from our current SDK?

**Comment by nbaulesglobalsolutions** [comment]
Will need all the help we can get from you guys to achieve that goal.

Please continu3 with all the updates.

All the best



NBaules

Get Outlook<https://aka.ms/sdimjr> for iOS_Nbaules
________________________________

**Comment by ppmtscory** [comment]
What are you looking to integrate that isn't available today with the current SDK?  What help are you needing specifically?

**Comment by ngoctr** [comment]
We still face this issue https://github.com/paypal/paypal-here-sdk-ios-distribution/issues/137 for older PayPalHere devices, we have got new devices and everything is fine.

**Comment by ppmtscory** [comment]
The new v2 SDK has been released and is available in this repo.

**Comment by nbaulesglobalsolutions** [comment]
[Inline image]

[Inline image]

<https://db.tt/dGZ16nKC>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
cashformula_freereport.pdf.zip

Zip via Dropbox


<https://db.tt/odGQSXPsw8>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Jul 14, 1 41 26 AM.txt

Text/Plain via Dropbox


<https://db.tt/mo6mMZMoGh>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Jul 22, 1 56 27 AM

Application/Octet-Stream via Dropbox


<https://db.tt/oMyXGrkDrg>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 05, 7 16 54 PM.txt

Text/Plain via Dropbox


<https://db.tt/eHTCgr6vac>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 06, 1 20 02 PM.png

Image via Dropbox


<https://db.tt/JvpLb7RoZx>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
Blog Conservation Law Foundation.pdf

Pdf via Dropbox


<https://db.tt/BaGTP5AiXY>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 14, 5 04 39 PM

Application/Octet-Stream via Dropbox


<https://db.tt/mVHPCfA7YZ>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 14, 8 38 28 PM

Application/Octet-Stream via Dropbox


<https://db.tt/6HYVfp2rF3>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 14, 8 42 26 PM

Application/Octet-Stream via Dropbox


<https://db.tt/Zpno2k6mON>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
nowcast_2017_0825.pdf

Pdf via Dropbox


<https://db.tt/z1qlAswY9B>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
E-Mail Funnels Webinar Replay!.pdf

Pdf via Dropbox


<https://db.tt/0I27Mf9qle>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 15, 1 46 46 AM.txt

Text/Plain via Dropbox


<https://db.tt/X4ipqwAkTn>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
File Aug 15, 12 47 53 AM

Application/Octet-Stream via Dropbox


<https://db.tt/GRfBPWTnVY>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
My Mobile Money Pages.pdf

Pdf via Dropbox


<https://db.tt/YJHXvODhmw>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
Untitled.pdf

Pdf via Dropbox


<https://db.tt/y88ayNLjgl>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
True Market Insiders.pdf

Pdf via Dropbox


<https://db.tt/Sh1sYNycYk>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
10k Every Day App.pdf

Pdf via Dropbox


<https://db.tt/QDGgKBnDtL>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
Electronics, Cars, Fashion, Collectibles, Coupons and More eBay.pdf

Pdf via Dropbox


<https://db.tt/xVZ1zJY3hx>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
The Conversion Pros Overview Page.pdf

Pdf via Dropbox


<https://db.tt/AV9tqlzhGi>
[https://s.yimg.com/nq/storm/assets/enhancrV2/23/logos/dropbox.png]
how to modify a picture in.alhea.com.pdf

Pdf via Dropbox





Sent from Yahoo Mail for iPad<https://overview.mail.yahoo.com/?.src=iOS>
