### ISSUE TITLE
Paypal here cannot login API with merchant production account 

### ISSUE THREAD

**Issue by thekingbk90** [paypal/paypal-here-sdk-ios-distribution#142]
I'm in UK. I have a problem with paypal here API. It work with my sandbox account without my live account.

With Sandbox account (name Ryan) I used this link => It worked:
https://www.sandbox.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri=https://devm2.nhubinh.com/webpospaypal/config/paypalsignin/&client_id=AU9fItE20_S6mZNKKyIYGwb0p9k5EFfvVBvXT4yI1tcQokAWWqw9AxEdOA3GLdZHLDW5SMdil9rGdxpq

With Live account I used this link => Error: invalid scope
https://www.paypal.com/signin/authorize?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri=https://pmvape.co.uk/webpospaypal/config/paypalsignin/&client_id=AaROz0chaNxlK1cwItqOWoEk3A76ABdx3uCVzFTcm4xASwRU07Ro3-HKcE9z01qjUCVBZ2v4jqWsMp1A

I'm sure that my live account is bussiness, my Paypal app has enough paypal here permission, and callback url was filled.
In Addition, My live paypal merchant account can work with Paypal here app (from Apple Store)
Screenshots:
https://prnt.sc/h615la
https://prnt.sc/h615u6
https://prnt.sc/h615y9

Anyone can help me.

Regards,
Johnny

**Comment by ppmtscory** [comment]
In your REST App on developer.paypal.com, you didn't select the PayPal Here scope or any of the address scopes underneath the Log in with PayPal section.  Since you are using those scopes in the redirect to the /authorize endpoint, they need to be selected on your REST App.  The scopes you selected for the sandbox part of your REST App don't automatically transfer to the Live part of your REST App.

**Comment by thekingbk90** [comment]
I have already checked live app setting. Paypal here scope was choosen already.
https://prnt.sc/h780x7
:(

**Comment by thekingbk90** [comment]
Thank you

I got it lastnight. 
But there is another problem, after call back
https://pmvape.co.uk/webpospaypal/config/paypalsignin/?code=C21AAG0Wy8uttQND5D4pjCo8tIy6bCiohsYieiZD94BL32q3WLbK69H8R6E6Gzav4josTGX5ZDowspqbqfD8Zwz4-QVb_tJSA&scope=https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes%2Fbusiness%20https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalhere%20address%20email%20openid

Exception: $tokenInfo = OpenIdTokeninfo::createFromAuthorizationCode($params, null, null, $apiContext);

I'm sure $param and $apiContext is ok because dev account works well

Screenshot: https://prnt.sc/h7l4du

**Comment by thekingbk90** [comment]
Well, this problems was fixed,
I have to set environment is live in PHP code
       $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                $clientId,
                $clientSecret
            )
        );
        $apiContext->setConfig(array(
            'mode' => 'live'
        ));
It's missed in dev guide:
https://developer.paypal.com/docs/api/quickstart/environment/
Note, Java, Python, Ruby, .NET need to be set enviroment without PHP :))
