### ISSUE TITLE
PPHTransactionManager encryptedCardData

### ISSUE THREAD

**Issue by rrepaka** [paypal/paypal-here-sdk-ios-distribution#144]
Do you have any code samples for  encryptedCardData() method ?

**Comment by ppmtscory** [comment]
If you're integrating with the SDK itself, then you wouldn't need to use this method at all as the card information is already encrypted at the time of the card swipe/insert/tap.

**Comment by rrepaka** [comment]
Yes , card information is encrypted at the time of swipe. 
Sorry i did not provide full information,  Basically we are trying to provide a deals/ promotions based on customer credit card , for that we are asking some help from you guys.

if you have any examples please share it with us.

**Comment by ppmtscory** [comment]
There's `PPHTokenizedCustomerInformation` as a part of the `PPHTransactionRecord` which contains a `customerId`.  This ID is specific to the card used for the payment so it would be the same each time that particular card is used.  This is usually what folks use for loyalty/promotions/etc.

**Comment by rrepaka** [comment]
Thanks for sharing this info. can we get this Object without processing any transaction ? the reason is  customer swiped his credit card just to know his loyalty / promotions without any transaction amount .

How do we get this object ?

**Comment by nbaulesglobalsolutions** [comment]
No. I don’t think I have one.. how do I get one?



Sent from myMail for iOS


Wednesday, November 22, 2017, 2:52 AM +0800 from notifications@github.com <notifications@github.com>:

Do you have any code samples for encryptedCardData() method ?

**Comment by rrepaka** [comment]
Hello ppmtscory,
Sorry, we are trying to get credit card information without any transaction amount and trying to avoid back end call if possible . Is there any method in paypalHereSDK so that we an show loyalty/promotions based on card data

**Comment by ppmtscory** [comment]
You would need to store that information when it's available and then if the customer wants to know, you would look in your DB to determine what their loyalty balance is.  There's no way to run a transaction for a $0 amount.  You'd store the customer ID alongside some other identifying info (card last 4 maybe?) so that when the customer wants to know, you simply need to ask for that info, type into your app, and make the call to your DB.

**Comment by rrepaka** [comment]
Thanks a lot for your help

**Comment by nbaulesglobalsolutions** [comment]
Ok will do it right away..

Thanks



NBaules



Sent from myMail for iOS


Wednesday, November 22, 2017, 6:45 AM +0800 from rrepaka <notifications@github.com>:

Thanks a lot for your help
