### ISSUE TITLE
Submit Papal payment data

### ISSUE THREAD

**Issue by nbaulesglobalsolutions** [paypal/paypal-here-sdk-ios-distribution#151]
[coinwidget.com-master.zip](https://github.com/paypal/paypal-here-sdk-ios-distribution/files/1617789/coinwidget.com-master.zip)

**Comment by ppmtscory** [comment]
It is unclear what is being requested here.  Please take a peek at our new SDK that was just published and/or open a new issue with all the relevant details for us to take a look into your issue.
