### ISSUE TITLE
Use swipe for non-payment in Paypal IOS SDK

### ISSUE THREAD

**Issue by afarouk** [paypal/paypal-here-sdk-ios-distribution#168]
We are using the paypal chip reader (older model)
https://www.paypal.com/us/webapps/mpp/credit-card-reader-how-to/chip-card-reader
with an IOS app via the ios SDK/Bluetooth. 
Our payments are working fine. However, we would also like to use the swipe function for approximate customer identification. 

**Our plan**
1. We begin monitoring the card reader. 
2. Customer swipes the card (chip or no-chip)
3. We get a callback (didSwipeCard... )
4. We take the encrypted track information to compare with previous swipes. 
NOTE: We do not want to decrypt the track information in anyway or use it for payments etc. We only want to use it for comparison to a previously swiped credit card. We could also use 'masked' card info for this purpose instead of raw tracks. 

**Where we are stuck**
We have implemented the listeners but we do not see a callback. Also, the reader directs customers with chip cards to insert the card, and older stripe only cards are simply ignored. It appears that our card reader is configured not accept swipe cards at all. 

**Questions**
Q1:  Is it possible to put the card reader in swipe only-mode ? 
Q2: If so, can you please direct us to some code example or API documentation (we are familiar with the usual paypayhere sdk and are successfully using it for payments). 

Finally, we are able to use the pattern above for card readers from other vendors (Worldpay), but we would like to stick to paypal if possible. 

Thank you for your help

**Comment by ppmtscory** [comment]
This is not something that's implemented currently but we will take this as feedback to consider future development.

**Comment by afarouk** [comment]
Meanwhile, anyone else trying to achieve this functionality ( credit card swipe for identification of repeat user) and not wanting to wait for Paypal to implement this, Vantiv/Worldpay already support this on their devices. Feel free to contact me for details.
