### ISSUE TITLE
SampleApp: “PPHSDKSampleApp” does not contain a valid Info.plist

### ISSUE THREAD

**Issue by civocr** [paypal/paypal-here-sdk-ios-distribution#176]
Hey there, 

I'm trying to run the sample app using xcode 9.2.

Trying to run on a device, i get the following error:

“PPHSDKSampleApp” does not contain a valid Info.plist, so it cannot be installed on Jason's iPad

(“CFBundleExecutable” is not specified)

**Comment by snehanshuashar** [comment]
@civocr Thank you for trying out the sample app.
Please follow these steps to resolve the error:

- Open the info.plist file in Xcode
- Delete the entry for Executable file
- Add Row to the Info.plist
- Set the key for the new row to CFBundleExecutable and the value to $(EXECUTABLE_NAME)

That should resolves the error.

**Comment by civocr** [comment]
I've tried to do that in the sample app's Info.plist (received the same error)
Added it to the Paypal SDK's Info.plist and I get the following error:

The file “PPHSDKSampleApp” couldn’t be opened because you don’t have permission to view it.

**Comment by snehanshuashar** [comment]
@civocr Please refer to this video. This has done the trick for all our partners using the sample app.

https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/KnownIssues/CFBundleExecutable_Fix.mov

**Comment by civocr** [comment]
thanks, I've gotten it to run a couple of times but seems I either come back to the same error (even though I do the same steps over and over) especially adding other pods.

**Comment by civocr** [comment]
Looking at the contents of the app, the info.plist is attached
[Info.txt](https://github.com/paypal/paypal-here-sdk-ios-distribution/files/1709039/Info.txt)

**Comment by ppmtscory** [comment]
Based on your other issue of running payments, I'm going to close this out.  Until we figure out why this is happening, you'll likely need to go through these same steps each time you do a `pod install`.
