### ISSUE TITLE
Issue in install pos file

### ISSUE THREAD

**Issue by sanjukta1993** [paypal/paypal-here-sdk-ios-distribution#181]
I cannot install the pod 'PayPalHereSDKv2'...
I use swift4.
After installing in the terminal I get error like this:

[!] Unable to find a specification for `PayPalHereSDKv2`

[!] Automatically assigning platform ios with version 9.0 on target PPHSDKSampleApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Please help me to solve this problem.Its very urgent

**Comment by snehanshuashar** [comment]
Can you try “pod update” please?

**Comment by sanjukta1993** [comment]
Thanks a lot.
