### ISSUE TITLE
Send authorization header with refresh URL request

### ISSUE THREAD

**Issue by maxpaynestory** [paypal/paypal-here-sdk-ios-distribution#184]
Please guide us how to send authorization header with refresh URL request using paypal here sdk.

**Comment by ppmtscory** [comment]
That would all be done on your server side.  As long as you create a valid `sdkCredential` to include the refresh URL, then the SDK would automatically reach out to your refresh URL and then you'd handle the refresh server-side.

**Comment by maxpaynestory** [comment]
Our refresh URL is secured with Basic Authentication, how to supply Basic authentication header using your sdk?

**Comment by ppmtscory** [comment]
I'm not aware of a way to modify the request that the SDK sends when it reaches out to your refresh URL.  If you need a custom setup for this, then you can handle the refresh on your own as well.  You'll simply reach out when needed and pass the new token back into the `initializeMerchant` call.  Access tokens are valid for 8 hrs so you'd simply need to trigger that on your side.

**Comment by ppmtscory** [comment]
Else, the `sdkCredential` class will also take in your client credentials and refresh token if you'd like to use those and have the SDK reach out to PayPal directly.  These would only be stored in the cache on the device and should never be stored on the device itself.
