### ISSUE TITLE
Can we skip Payment complete screen  in order to speed up the user activity?

### ISSUE THREAD

**Issue by kumarsharma** [paypal/paypal-here-sdk-ios-distribution#191]
Hello Sir,

We are using PayPal Here SDK in our app with PPH card reader. We want to skip the payment complete screen (the screen which shows the Email, Text, No Receipt... options) after completing a payment to speed up the user activity.

Could you please let me know if there is an option for that?

**Comment by DJ92** [comment]
Unfortunately, that's not possible as of yet. In order to skip that part, the only workaround is to use an auth/capture flow for processing payments. That being said, it is definitely on our roadmap for this year.

**Comment by rrepaka** [comment]
Hello KumarSharma,

I think In SDK2.0 also Paypal is not providing this feature.

**Comment by kumarsharma** [comment]
Hello,

Is it! Actually i'm in the process of integrating SDK2.0. I hope they provide this in SDK2.0 as they said. Soon SDK integration is going to be finished in my side so will know whether we can achieve this.

**Comment by neogeo947** [comment]
Hi @DJ92, you'd mentioned on 1st March that this feature "is definitely on our roadmap for this year". Would you know approximately when that would be this year? We're designing an app that relies on this. Any indication would be massively helpful! Thanks

**Comment by DJ92** [comment]
Hi @neogeo947, yes this feature is available. We need you to acknowledge the suppression of receipts in a mail to be PCI Compliant. I can send out the acknowledgement if you can provide the Merchant name and id's you want me to send it to. 

Thanks.

**Comment by marcospolanco** [comment]
@DJ92 regarding the suppression of receipts, how exactly do we contact you with the requisite acknowledgment? Thx.

**Comment by nbaulesglobalsolutions** [comment]
Hello Marco,

Thanks for your email inquiring About how to get in touch regarding some site requisits I’m hoping would finally solve this issue ive been having in accessing what I’m told are accumulated
 earnings online I’m still working on trying to activat3 through PayPal..

You can contact me directly via my cellphone @09175985609 or continue to use my listed email account on epadfin@outlook.com

Thank you and look forward to hearing from you... Again, Happy New Year!


NBaules




Sent from Yahoo Mail for iPad<https://overview.mail.yahoo.com/?.src=iOS>


On Tuesday, January 1, 2019, 3:37 AM, Marcos Polanco <notifications@github.com> wrote:

@DJ92<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDJ92&data=02%7C01%7C%7C54d3876495c641df6eb408d66f57750f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636818818740612078&sdata=JFsnzlFDociW9L%2BcK%2BvunKt5RSU7Dp0J5l8pGTr1UPk%3D&reserved=0> regarding the suppression of receipts, how exactly do we contact you with the requisite acknowledgment? Thx.
