### ISSUE TITLE
PayPalRetailSDK.h  #import <UIKit/UiKit.h> ==> Error when running pod install with Xcode 9.2

### ISSUE THREAD

**Issue by nguyenhoang57** [paypal/paypal-here-sdk-ios-distribution#192]
Now SDK importing : #import <UIKit/UiKit.h> .  ==> Wrong 
I need fix now because when i pod install  Xcode running error.

**Comment by DJ92** [comment]
The correct library is #import <UIKit/UIKit.h>. Please check your pod version/typos. If the problem persists, please send your console logs.
