### ISSUE TITLE
PPH SDK V2.0: Framework not found SimpleKeychain

### ISSUE THREAD

**Issue by kumarsharma** [paypal/paypal-here-sdk-ios-distribution#195]
Hello Sir,

I am trying to integrate PPH SDK V2.0 in an app.

Firstly, I was trying to run SampleApp downloaded from https://github.com/paypal/paypal-here-sdk-ios-distribution. After installing pods, I got this message in the terminal "Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.". 

When I tried to run the sample-app I am getting following error message :

--------------
ld: warning: directory not found for option '-F/Users/user/Library/Developer/Xcode/DerivedData/PPHSDKSampleApp-arsoxasucrwycxguumhbctsqgqkg/Build/Products/Debug-iphoneos/SimpleKeychain'
ld: framework not found SimpleKeychain
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error 1: framework not found SimpleKeychain
---------------

Could any please let me know how can I resolve the error?

**Comment by DJ92** [comment]
Hi, happy to help. 
Can you try running a pod update followed by a pod install? 
If that doesn’t work, can I take a look at your pod file? 
Also, which merchant are you integrating for?

**Comment by kumarsharma** [comment]
Hello Sir,

I tried running pod update followed by a pod install but it showed the following error:
______________________________________

[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down
______________________________________

Following is the content of the pod file:
______________________________________
platform :ios, '8.1'

inhibit_all_warnings!
use_frameworks!

workspace 'PPHSDKSampleApp'

target 'PPHSDKSampleApp' do
    project 'PPHSDKSampleApp.xcodeproj'
    pod 'PayPalHereSDKv2'
end
______________________________________

**Comment by DJ92** [comment]
The commands are working. Check for connectivity issues on your side.

**Comment by kumarsharma** [comment]
Ok, its working by directly importing PayPalRetail SDK into the project. But while building I am getting following errors. Am I missing any framework to be added to the project? It would be really helpful if you could guide in this regard.

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SwiperController", referenced from:
      objc-class-ref in PayPalRetailSDK(PPRoamAudioReader.o)
  "_OBJC_CLASS_$_JSContext", referenced from:
      objc-class-ref in PayPalRetailSDK(PPManticoreEngine.o)
  "_OBJC_CLASS_$_RUA", referenced from:
      objc-class-ref in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
  "_OBJC_CLASS_$_RUAEnumerationHelper", referenced from:
      objc-class-ref in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
  "_JSValueProtect", referenced from:
      -[PPDeviceScanner getBTList:] in PayPalRetailSDK(PPDeviceScanner.o)
      -[PPDeviceScanner startScan:] in PayPalRetailSDK(PPDeviceScanner.o)
      -[PPIngenicoBluetoothDevice removed:] in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
      -[PPIngenicoBluetoothDevice disconnect:] in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
      -[PPManticoreNativeInterface http:callback:] in PayPalRetailSDK(PPManticoreNativeInterface.o)
      -[PPRetailNativeInterface collectSignature:withCallback:] in PayPalRetailSDK(PPRetailNativeInterface.o)
      -[PPRetailNativeInterface offerReceipt:withCallback:] in PayPalRetailSDK(PPRetailNativeInterface.o)
      ...
  "_JSValueUnprotect", referenced from:
      -[PPDeviceScanner getBTList:] in PayPalRetailSDK(PPDeviceScanner.o)
      -[PPDeviceScanner stopScan] in PayPalRetailSDK(PPDeviceScanner.o)
      -[PPIngenicoBluetoothDevice removed:] in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
      -[PPIngenicoBluetoothDevice done] in PayPalRetailSDK(PPIngenicoBluetoothDevice.o)
      ___44-[PPManticoreNativeInterface http:callback:]_block_invoke in PayPalRetailSDK(PPManticoreNativeInterface.o)
      ___57-[PPRetailNativeInterface collectSignature:withCallback:]_block_invoke in PayPalRetailSDK(PPRetailNativeInterface.o)
      ___53-[PPRetailNativeInterface offerReceipt:withCallback:]_block_invoke in PayPalRetailSDK(PPRetailNativeInterface.o)

**Comment by kumarsharma** [comment]
Hello,

I missed the following frameworks which are there under frameworks folder in the SDK repository:

PPHR_BLE.framework	
PPHSDK_BLE.framework
PPHSwiper.framework

Also, I needed to add the "JavaScriptCore" framework into the project.

Now, the problem is when I try to initialize the SDK using SdkCredential, the app is crashing. Following is the crash message:
___________________________________________________
*** Terminating app due to uncaught exception 'PPManticoreNativeInterfaceException', reason: 'Manticore engine encountered an error.
Message: undefined is not an object
JS Stack:
undefined'
___________________________________________________

**Comment by DJ92** [comment]
It looks like a dependency/framework missing issue. The pod update and install commands should get all the required ones. You can compare to the sample app ones as well to find the missing ones.
