### ISSUE TITLE
Invalid token issue

### ISSUE THREAD

**Issue by rrepaka** [paypal/paypal-here-sdk-ios-distribution#199]
We are trying to upgrade to PayPalHereSDKv2/Release  from PaypalHereSDK.

We are using below method for initalising PaypalHere SDK 

    [PayPalHereSDK setupWithCompositeTokenString:token
                           thenCompletionHandler:^(PPHInitResultType status, PPHError *error, PPHMerchantInfo *info) {
                               [[ApplicationData sharedInstance]hideHUD];
                               if (error) {
                                   UIAlertView *alert = [[UIAlertView alloc]initWithTitle:StringAlertTitleRequestFailed message:error.localizedDescription delegate:nil cancelButtonTitle:StringAlertButtonDone otherButtonTitles: nil];
                                   [alert show];
                               } else {
                               }
                           }];

the token is generated by API server.

we are using below method when we upgraded SDK to PaypalRetailSDK

[ PayPalRetailSDK initializeMerchant:token repository:@"" completionHandler:^(PPRetailError error, PPRetailMerchant merchant) {
        [[ApplicationData sharedInstance]hideHUD];
                                       NSLog(@"error = %@",error.description);
        if (error) {
            UIAlertView *alert = [[UIAlertView alloc]initWithTitle:StringAlertTitleRequestFailed message:error.developerMessage delegate:nil cancelButtonTitle:StringAlertButtonDone therButtonTitles: nil];
            [alert show];
        } else {
        }
    }];
    

It says Invalid token.

Questions

1. are we using the correct method in PaypalRetailSDK ? 

2. Do we need to modify any logic in token creation ?

I can share token generated by API server if you want , the same token is working fine with OLD PaypalHereSDK.

**Comment by DJ92** [comment]
You could use the piece from the sample app. Here's the snippet for your initializeCall() -
PayPalRetailSDK.initializeMerchant(withCredentials: sdkCreds) { (error, merchant) in
            if let err = error {
                self.activitySpinner.stopAnimating()
                print("Debug ID: \(err.debugId)")
                print("Error Message: \(err.message)")
                print("Error Code: \(err.code)")

                // The token did not work, so clear the saved token so we can go back to the login page
                let tokenDefault = UserDefaults.init()
                tokenDefault.removeObject(forKey: "ACCESS_TOKEN")
                self.performLogin()
            }

            print("Merchant Success!")
            self.activitySpinner.stopAnimating()
            self.initMerchantButton.setImage(#imageLiteral(resourceName: "small-greenarrow"), for: .disabled)
            self.initMerchantButton.isEnabled = false
            self.merchInfoView.isHidden = false
            self.merchEmailLabel.text = merchant!.emailAddress

            // Save currency to UserDefaults for further usage. This needs to be used to initialize
            // the PPRetailInvoice for the payment later on. This app is using UserDefault but
            // it could just as easily be passed through the segue.
            let tokenDefault = UserDefaults.init()
            tokenDefault.setValue(merchant!.currency, forKey: "MERCH_CURRENCY")

            // Add the BN code for Partner tracking. To obtain this value, contact
            // your PayPal account representative. Please do not change this value when
            // using this sample app for testing.
            merchant?.referrerCode = "PPHSDK_SampleApp_iOS"

            //Enable the connect card reader button here
            self.connectCardReaderBtn.isHidden = false
        }
        
    }
