### ISSUE TITLE
crash PayPalRetailSDK initializePPHRetailMerchant:completionHandler

### ISSUE THREAD

**Issue by gmann1** [paypal/paypal-here-sdk-ios-distribution#200]
v2.0.1201805

```
        PayPalRetailSDK.initializePPHRetailMerchant(merchant) { (e, m) in
            //
        }
```

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f7411e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010edd6031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f7810bc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010f654951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010f6547db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   omni                                0x000000010af03316 +[PayPalRetailSDK initializePPHRetailMerchant:completionHandler:] + 1280

**Comment by snehanshuashar** [comment]
@gmann1 initializePPHRetailMerchant is reserved for First-Party (PayPal) use. SDK integrations should use [InitializeMerchantWithCredentials](https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/SampleApp/PPHSDKSampleApp/InitializeViewController.swift#L132).

**Comment by gmann1** [comment]
@snehanshuashar ok, thanks for getting back to me! I'm trying to use a composite token with sdk v2, is that something that is still supported?

**Comment by snehanshuashar** [comment]
@gmann1 yes, you can use `initializeMerchant` (the one without credentials) for a composite token :)

**Comment by gmann1** [comment]
@snehanshuashar sorry to bother you again, but I was looping back around to this and meant to ask: what is the `repository` (String) parameter referring to when using intializeMerchant (the one without credentials)? I got it working when setting it to "production" but I can't find in the docs what this parameter is referencing.
