### ISSUE TITLE
Can we hide "PaymentComplete( Do you want receipt ?) screen in PayPalHereSDK, 

### ISSUE THREAD

**Issue by rrepaka** [paypal/paypal-here-sdk-ios-distribution#201]
We have integrated PayPalHereSDK with our app , we currently show  Payment Complete , Do you want receipt ? screen.

But couple of my businesses wants to suppress this screen ( Do not show this screen to customers after transaction processed)

Do we have any options in SDK to suppress this screen ? 
![img_0083](https://user-images.githubusercontent.com/15839195/37995766-62230fee-31ca-11e8-827c-56f43f926e18.PNG)

**Comment by kumarsharma** [comment]
Hello,
We too wanted same thing but unfortunately its not possible in SDK V 1.6. See this link https://github.com/paypal/paypal-here-sdk-ios-distribution/issues/191. They suggested us to integrate SDK V 2.0 which lots more features.

Thank you.
