### ISSUE TITLE
PPH SDK V 2.0 Transaction Cancelled

### ISSUE THREAD

**Issue by kumarsharma** [paypal/paypal-here-sdk-ios-distribution#202]
Integration to PPH SDK 2.0 was ok. During payment, after inserting/swiping card the message "Transaction Cancelled" pops up as follows. Not sure why its happening. Also not getting response under completion handler so unable to find the reason why the transaction is getting cancelled. Any suggestions?

<img width="431" alt="screen shot 2018-03-28 at 9 23 48 pm" src="https://user-images.githubusercontent.com/600028/38041028-65d3f84c-32ce-11e8-9b32-a5d3bfe0fbb5.png">

**Comment by DJ92** [comment]
Is this live or Sandbox ? And just to confirm, you're using the auth/capture flow right?

**Comment by kumarsharma** [comment]
Its live and authcapture is false. Below is the code:

PPRetailTransactionBeginOptions *options = [[PPRetailTransactionBeginOptions alloc] init];
options.showPromptInCardReader = YES;
options.showPromptInApp = YES;
options.isAuthCapture = NO;
[self.ppTransactionContext beginPayment:options];

**Comment by DJ92** [comment]
Any correlation/debug id you can share? It's in the txnRecord object

**Comment by kumarsharma** [comment]
Yes I found the issue why it was cancelled. I was trying to give a long unique string as an invoice number which was not able to generate the invoice. However, still I am not getting  responses under completion handler.

**Comment by DJ92** [comment]
Yes, the invoice field is limited to 25 chars. If you can share a correlation/debug id, I can look into the logs to find a root cause.

**Comment by kumarsharma** [comment]
Even after completing payment I am not getting response under completion handler so can't close the sale as I am not getting invoice id and transaction id. 

Following is the detail of a denied transaction. But still I should get a response under comletion handler right. Is there any other way to get response?

#############################
 "statusCode": 200,
    "body": {
        "specialOffersRedeemed": [],
        "correlationId": "758f966087025",
        "invoiceId": "INV2-ZQPB-2NC4-8QX5-86UA",
        "paymentAction": "sale",
        "payerInfo": {},
        "warnings": [
            {
                "message": "Please try another card",
                "developerMessage": "This credit card cannot be processed by PayPal",
                "errorCode": "580031"
            }
        ],
        "authCode": "8A023434910a485F95F4A4BB35A43034",
        "transactionHandle": "958087881S425152Y",
        "responseCode": "5150"
    },
    "headers": {
        "Server": "Apache",
        "Paypal-Debug-Id": "758f966087025, 758f966087025",
        "Content-Length": "385",
        "Connection": "close",
        "Date": "Thu, 29 Mar 2018 05:06:27 GMT",
        "Vary": "Authorization",
#############################

**Comment by ppmtscory** [comment]
@kumarsharma are you seeing the receipt options screen for the payment denial at all?  It should have a message that the transaction was denied and an options for SMS or email receipt.  If you're not seeing this screen, then something is amiss with your view hierarchy to where it's not able to be shown.  You will not get a callback to your completion handler until an option is pressed on that receipt screen.  Please make sure you are implementing the `PPHRetailSDKAppDelegate` so that `getCurrentNavigationController()` can be utilized by the SDK.  This is implemented on the `PaymentViewController` of the sample app if you'd like to see what I'm referring to.

**Comment by kumarsharma** [comment]
Hello,
Thanks for pointing out the PPHRetailSDKAppDelegate implementation. I missed that!! Now after implementing PPHRetailSDKAppDelegate I am getting receipt screen and all call the backs. But we wanted to skip the receipt screen where option to sms, email etc appear to speed up the process. We were hoping that this will be possible in SDK 2.0. Is there any option for that?

**Comment by ppmtscory** [comment]
Not currently, no, but it's on the very short term roadmap so stay tuned.  You can keep a watch on issue #201 as we'll post an update there when it's been implemented and tested.

**Comment by kumarsharma** [comment]
Thanks
