### ISSUE TITLE
Receipt screen dismisses the whole view hierarchy

### ISSUE THREAD

**Issue by kumarsharma** [paypal/paypal-here-sdk-ios-distribution#207]
Upon completing payment the receipt screen appears and when it gets dismissed the view hierarchy is also getting dismissed. 

I have a login VC and on top of this presenting a menu VC after log in. But this receipt screen is dismissing everything which is taking me to the login screen unintentionally. In previous version of PPH SDK (1.6) it was not there. Only receipt screen was used to dismissed.

Is that something a bug or I am doing something wrong?

**Comment by DJ92** [comment]
Are you saying this issue started with a newer release of the v2.0 SDK? For now receipts don't break the VC hierarchy as far as we've tested and integrated with other merchants. If you provide a few details, we can help you sort out the VC issue.
