### ISSUE TITLE
Connecting to bluetooth device issues

### ISSUE THREAD

**Issue by gmann1** [paypal/paypal-here-sdk-ios-distribution#209]
sdk version 2.0.1201805
iOS 11.3

When bluetooth is off:

1. searchAndConnect spins indefinitely. No error displays. Would expect a timeout with a message that explains to user that cannot find a device because maybe bluetooth is off?

2. connectToLastActiveReader errors out immediately, which is what I would expect. However no where in the error message does it state for the user to make sure that bluetooth is on:

"Sorry we could not connect to this reader... Please check the card reader is turned on and the battery is charged"

When bluetooth is on and NO device is connected:

1. searchAndConnect does not error immediately but after a few seconds. No where in the error message does it state for the user to make sure that bluetooth is on:

"Sorry we could not connect to this reader... Please check the card reader is turned on and the battery is charged"

2. connectToLastActiveReader does same thing as when bluetooth is just off (see above)

**Comment by DJ92** [comment]
I am looking at the use case reported. The second one seems like the same as Bluetooth OFF. I've tested this on our end with the latest build. The searchAndConnect & connectToLast work as expected. The bluetooth off messaging is a bit off but we have included that as a feedback. Thanks

**Comment by gmann1** [comment]
@DJ92 When bluetooth is off searchAndConnect 'searches' indefinitely. The is working as expected? Shouldn't it indicate to the user their bluetooth is off?

**Comment by DJ92** [comment]
Yup I agree. We have it marked as an enhancement in our internal tasks. Will update once there's a new release :)

**Comment by gmann1** [comment]
awesome guys! great work
