### ISSUE TITLE
Random errors when processing transactions against sandbox

### ISSUE THREAD

**Issue by hb-tpfister** [paypal/paypal-here-sdk-ios-distribution#211]
Hi, 

during development and testing with mocked data I am getting weird errors when processing transactions against the sandbox environments. The following three examples capture what kinds of errors I am running into.

```
correlationID: - 
code: 600000
domain: retail
message: "Downstream REST response has no entity to read"
debugID: -

correlationID: 24fae95b5e560 
code: 500
domain: retail
message: "domain: retail, code: 500, message: , debugId: , details: "
debugID: - 

correlationID: 35a7b2d7c8110
code: 580022
domain: retail
message: "empty TxnId&PPAPI RC: 10536&Pimp RC: 3204&AuthCode: null&ResponseCode: null"
debugID: a6883ae8b7a56
```

As the mocked calls are identical and I do get successful transactions I am wondering why sometimes there are these errors. So far I have not been able to see a pattern. 

Any input would be helpful.

Thanks, 
Thorsten

**Comment by hb-tpfister** [comment]
Hi, 

thanks for the quick response. Sure, I'm testing Sale/Auth (no capture). I'm not sure what merchant data you need to make identification simple for you, can you please point me in a direction? To give you an example correltationID of a working test `7e419d308cc6b,89ac06302d1c2`. I'm doing that one as a sanity check and encounter the above errors. 

Thanks!

**Comment by DJ92** [comment]
We're investigating this. Thanks for reporting.

**Comment by DJ92** [comment]
Quick update, this has been fixed for all payment types except MasterCard as of this morning.

**Comment by hb-tpfister** [comment]
Thanks!
