### ISSUE TITLE
App crash after authentication, redirect to iOS App

### ISSUE THREAD

**Issue by AjitPrajapati** [paypal/paypal-here-sdk-ios-distribution#215]
Hi, App is crashed while returning back to AppDelegate, in performLogin() function.
EXC_BAD_ACCESS (code=1, address=0x0)

Here is log:
objc[793]: Class RP45BTDeviceManager is implemented in both /private/var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK (0x101809d70) and /var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/PPHSDKSampleApp (0x101196f58). One of the two will be used. Which one is undefined.
objc[793]: Class RUACertificateFilesVersionInfo is implemented in both /private/var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK (0x101809de8) and /var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/PPHSDKSampleApp (0x101196fd0). One of the two will be used. Which one is undefined.
objc[793]: Class CertificateInfo is implemented in both /private/var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK (0x101809e10) and /var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/PPHSDKSampleApp (0x101196ff8). One of the two will be used. Which one is undefined.
objc[793]: Class RUADevice is implemented in both /private/var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK (0x101809e60) and /var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/PPHSDKSampleApp (0x101197048). One of the two will be used. Which one is undefined.
objc[793]: Class BaseKeyMap is implemented in both /private/var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK (0x101809ed8) and /var/containers/Bundle/Application/93E3D235-DA2A-4A91-870A-2DF1706CA0F5/PPHSDKSampleApp.app/PPHSDKSampleApp (0x1011970c0). One of the two will be used. Which one is undefined.

**Comment by ppmtscory** [comment]
There is a bug with Apple and Xcode which is causing this.  The workaround until they fix it is to add a `?` after `Any` in the function `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool` , like so: `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any?) -> Bool`.  Once you add this, you'll likely see a Warning for it but it should build and run just fine.

**Comment by hardikdarji** [comment]
thanks, the lot... it works, with a warning, without a crash
