### ISSUE TITLE
PPRetailInstrumentInterface not found

### ISSUE THREAD

**Issue by ludogoarin** [paypal/paypal-here-sdk-ios-distribution#222]
Hi - I am unable to build the project because PPRetailInstrumentInterface resources aren't found in the Pod.

I am getting this error for these two imports: 'PPRetailInstrumentInterface/PPRetailInstrumentationDelegate.h' file not found

#import <PPRetailInstrumentInterface/PPRetailInstrumentationDelegate.h>
#import <PPRetailInstrumentInterface/PPRetailInstrumentationRouter.h>

**Comment by DJ92** [comment]
Hi, 

This has been fixed as a part of the latest .811 release. Can you try a pod update and check?

**Comment by DJ92** [comment]
Interesting. I just tried on my repo 

```dhejoshi$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.5.2 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.2

Analyzing dependencies
Downloading dependencies
Using CocoaLumberjack (3.4.2)
Using LogglyLogger-CocoaLumberjack (3.0.0)
Installing PPRetailInstrumentInterface (1.1.6)
Installing PayPalHereSDKv2 2.0.1201811 (was 2.0.1201808)
Using SimpleKeychain (0.6.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 5 total pods installed.

```
It works fine. Any screenshot of what you see in xcode?

**Comment by ludogoarin** [comment]
Ok I cleared the cache and ran pod update. It's now working and installing
all dependencies. You can close the ticket. Thank you.

**Comment by DJ92** [comment]
Perfect! Glad it worked,

**Comment by yomagic** [comment]
I have run pod update today and I am getting this same error. 

See screenshot attached.
![screen shot 2018-07-13 at 12 53 45](https://user-images.githubusercontent.com/37225382/42690375-de8a5d1e-869b-11e8-9ace-8153a71fe776.png)

My pod file looks like this:

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'APPNAME' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for APPNAME
  pod 'PayPalHereSDKv2'
  target 'APPNAMETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APPNAMEUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
