### ISSUE TITLE
Capture & Manual Entry together

### ISSUE THREAD

**Issue by vhghorecha** [paypal/paypal-here-sdk-ios-distribution#223]
Hello Folks,
I am not able to combine two customizations as described in SDK documentation. I want to use Capture & Manual entry together. There is no implementation or description for the same.

**Comment by DJ92** [comment]
Okay I see. This isn't documented but you would do the same manual entry for the Auth call as mentioned for the Sale in the documentation. The Capture is then done using the details that come back in the Auth Success. If you're testing this flow and facing any issues with capture do keep me posted.

**Comment by vhghorecha** [comment]
Hello Dheeraj,

Documentation says for Capturing authorizations, during the payment we need to set option "isAuthCapture" to true which is available in PPRetailTransactionBeginOptions and we can pass it to
beginPayment method like below.

```
// Setting up the options for the transaction.
let options = PPRetailTransactionBeginOptions()
options.showPromptInCardReader = true 
options.showPromptInApp = true 
options.preferredFormFactors = []  
options.tippingOnReaderEnabled = false
options.amountBasedTipping = false
options.isAuthCapture = false

// Activates the reader to show the payment options
tc.beginPayment(options)
```

But for manual entry we need to call continue method with CardInfo which directly process the payment and not the capture authorization like below.

```
let cardInfo = PPRetailManuallyEnteredCard.init()
cardInfo.setCardNumber("1234123412341234")
cardInfo.setExpiration("MMYYYY")
cardInfo.setCVV("123")
cardInfo.setPostalCode("12345")

tc.continue(with: cardInfo)
```

So my problem is that how to set isAuthCapture for Manual credit card entry??

**Comment by vhghorecha** [comment]
Hi,
But the document says that we need to call only "continue" method instead of "beginPaymet". Below is the text from the documentation.

> You can also enter a customer's credit card manually if needed. Follow the traditional route for processing a payment, except instead of creating transaction options and calling beginPayment(options), build a PPRetailManuallyEnteredCard instance and then pass that into the continue() method of the transaction context.

Now see your code it called both tc.continue and tc.beginPayment is it fine to call both as document states we don't need to call "beginPayment" and "transaction options"

**Comment by DJ92** [comment]
Hey, Good point. We'll change it in the documentation but that's how it works for the sale flow. This snippet should work for the capture flow. I'm gonna close this issue for now. Thanks
