### ISSUE TITLE
Unregistered Account - Sandbox 

### ISSUE THREAD

**Issue by hardikdarji** [paypal/paypal-here-sdk-ios-distribution#224]
Transaction is cancelled
The transaction is not success when insert chip card in PayPal HERE Reader .
Error Code: Optional("600006")
Error Message: Optional("Unregistered Account")
Debug ID: Optional("8c07e372217a")

  "correlationId": "106fbb60cbcae",
        "errorCode": 600006,
        "message": "Unregistered Account",
        "developerMessage": "The merchant account must be registered before taking payment.",
        "errorType": "pay/unregistered_account"

**Comment by nbaulesglobalsolutions** [comment]
I dont think so.. can you please advise on best way forward?

Thanks

Nbaules

Sent from Rainbow Mail for iOS


Thursday, 24 May 2018, 10:29 PM +0800 from notifications@github.com <notifications@github.com>:

Did you go through the onboarding flow for PayPalHere? I see the account didn't get registered for PPH on our side.

**Comment by DJ92** [comment]
Here's the reference to our documentation: https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding/ 

Let us know if there are any issues.

**Comment by nbaulesglobalsolutions** [comment]
Thanks... I hope im able to register. This might be the reason My account has t been receiving anything..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
