### ISSUE TITLE
Does PayPal SDK support swipe for tracks like WorldPay SDK does? 

### ISSUE THREAD

**Issue by afarouk** [paypal/paypal-here-sdk-ios-distribution#225]
WorldPay and other credit processing SDKs provide a 'swipe' to get encrypted tracks information. This can be useful for determining if the same card is being used (without knowing any information about the user). Does the PayPal SDK support this or is this a shortcoming or weakness of PayPal?

**Comment by DJ92** [comment]
Hi Alamgir,

As communicated before, if we have processed a credit card before and have tied it to a customer on our side, we come back with a customerID field that can be used to track loyalty, etc. on the Merchant’s side. As we strive to be PCI compliant, we simply process the payment and pass the details back to the merchant. Hope that answers your question.
