### ISSUE TITLE
Callback fails when user selects 'Find Another Reader'

### ISSUE THREAD

**Issue by yomagic** [paypal/paypal-here-sdk-ios-distribution#228]
Calling PPRetailDeviceManager::connectToLastActiveReader() brings up this screen:

![screen1](https://user-images.githubusercontent.com/37225382/40878514-5341aac2-668a-11e8-8f12-7815d21da3f0.png)

If the user chooses to find another device, they are presented with this screen:
![screen2](https://user-images.githubusercontent.com/37225382/40878515-535b10fc-668a-11e8-9b04-12f948705efa.png)

The problem I am facing is that when the user makes a new device selection from this screen, there is no callback to my app notifying it that device connection was successful. Instead the screen disappears and well that's it.

PPRetailDeviceManagerConnectionHandler is never called is this case. How can I fix this?

**Comment by DJ92** [comment]
Hi,

We've resolved this and will be fixed in our upcoming sdk version release. You can simply update to the new SDK and you will be all set. 

Thanks

**Comment by yomagic** [comment]
Hello!

This is wonderful news! When will the new SDK be available?

**Comment by DJ92** [comment]
It's available now. This issue has been resolved. Hence, closing this thread :)
