### ISSUE TITLE
Chip and Pin Transactions Not working

### ISSUE THREAD

**Issue by kodejack** [paypal/paypal-here-sdk-ios-distribution#233]
I'm trying to get my app working for transactions. Contactless works, swipe works, however, chip and pin always fails/ is declined.

Could there be a simple explanation for this?

**Comment by DJ92** [comment]
Hi,

Can we get some more information - 
1. Environment?
2. Which Card Type is this?
3. Also, what merchant is this integration for?

Thanks

**Comment by nbaulesglobalsolutions** [comment]
1. The system runs on iOS and Microsoft ; storage on google cloud, 

2. Use Payoneer MasterCard, Bank of Hawaii, Debt Visa

**Comment by nbaulesglobalsolutions** [comment]
💯 digital.

**Comment by DJ92** [comment]
Thanks for getting back. Is this on PayPal LIVE or Sandbox Environment?

**Comment by nbaulesglobalsolutions** [comment]
I had bought a new phone, iPhone X and had to switch sim but still leaving the old iPhone5 on for storage and app usage. Could this effect verification or authentication process? More so, will it have a negative impact on the network?

Thanks



NBaules

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DJ92** [comment]
Hi,

That shouldn't cause you any issues. It might ask you to confirm your device using a text/call, but that's about it. I can look into the chip and pin declines specifically if you have any correlationID's/PayPal-Debug-ID from the logs. 

Thanks
