### ISSUE TITLE
Objective C sample app missing

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#237]
Sure, swift is the new way and your SDK is v2... but you have to provide an Objective C sample app!! Many users would be maintaining an old Objective C app and upgrading the SDK version, so they need guidance just as much as swift developers do.

**Comment by DJ92** [comment]
Hi @pnemere, the sample app does exist in obj C. The Podfile would need to be updated to the latest version manually. https://github.com/paypal/paypal-here-sdk-ios-distribution/tree/beta/SampleAppObjC

Thanks
