### ISSUE TITLE
PPRetailPaymentDevice name returns nil

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#241]
Hi!

I've got a connection going in the SDK, calling getActiveReader to get the PPRetailPaymentDevice I'm connected to.

I'm able to retrieve:
[device serialNumber]
[device getVersionInfo]

However [device name] returns nil.

In the previous versions of the SDK there was a special friendlyName field, perhaps this is not implemented on the new one?!

Thanks!

**Comment by DJ92** [comment]
Hi @pnemere,

It should return an instance of this class: http://paypal.github.io/paypal-here-sdk-ios-distribution/Classes/PPRetailPaymentDevice.html Let me know if you don't see any fields that you need specifically for your implementation.

**Comment by pnemere** [comment]
What I'm saying is I already have a PPRetailPaymentDevice (as returned by getActiveReader). The device itself has a name method which returns nil.

**Comment by DJ92** [comment]
Hey @pnemere ,

I got your question. I think the `paymentDevice?.id` is the field that returns the friendly name.
Let me know if you have any further questions.

Thanks
