### ISSUE TITLE
What field to put user data in (so I can note something in a PPRetailInvoice and see it in the CSV downloaded from Activity in account)

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#245]
Hi!

I need to store some data with our invoices to help identify what they correspond to in our system. We store the PayPal transaction ID's on our end but it would be neater to be able to look at reports downloaded from https://business.paypal.com/merchantdata/reportHome?reportType=DLOG and see a "user" column in the CSV. We are able to do this with Stripe for example.

Having looked at the documentation, it seemed `additionalData` field in `PPRetailInvoice` would do this:

http://paypal.github.io/paypal-here-sdk-ios-distribution/Classes/PPRetailInvoice.html#//api/name/additionalData

However I have not found any way to see this `additionalData` field once the payment was made. I don't see it on any API documentation I have looked at, for example: PHP merchant SDK, or here: https://developer.paypal.com/docs/api/activities/v1/

Is there a better field I could be using? I see `metadata` in `PPRetailInvoice` is described as "Audit information of the resource. @readonly", not sure if that translates to something?

I see in the CSV generated by the activity reports page has some columns with the following names:
`Option 1 Name`, `Option 1 Value`, `Option 2 Name`, `Option 2 Value`

What are they for? Could I somehow fill those with my data?

Thanks!

**Comment by DJ92** [comment]
Hey @pnemere, currently for Additional fields to show up on Settlement Reports, we don't have a custom field. Although, the invoice number field in the createInvoice() is a 25 Char limit alphanumeric value. You can use this value to pass some extra information. For Eg: "Store123-Order456". Hope this helps.

**Comment by pnemere** [comment]
Thanks, that's what we'll do.
