### ISSUE TITLE
disable final summary screen for receipts and dismissing entire view hierarchy

### ISSUE THREAD

**Issue by uddinr** [paypal/paypal-here-sdk-ios-distribution#247]
is it possible to not show the final summary screen when taking a payment i am getting issues with the navigation controller as follows:

Warning: Attempt to present <UINavigationController: 0x14cdc4400> on <MyApp.MainNavigationController: 0x14c00c400> whose view is not in the window hierarchy!

**Comment by uddinr** [comment]
i have implemented PPHRetailSDKAppDelegate, but upon completion the entire view hierarchy is being dismissed? any idea why this is happening?

**Comment by uddinr** [comment]
after some investigation it seems the issue is related to having navigation views on top of other navigation views, it seems upon completion of a transaction every navigation view on the hierarchy is dismissed other than the main root view controller. 

could you please explain what you are doing in order to dismiss all view controllers as i would expect calling if the navigation controller is being set via the PPHRetailSDKAppDelegate method then the sdk calls dismiss by calling `getCurrentNavigationController().dismiss(.....)` why is the entire view stack being dismissed?

**Comment by uddinr** [comment]
is there any update or recommendations to this? otherwise we will be removing the support for paypal here and replacing with alternatives

**Comment by DJ92** [comment]
Hey @uddinr, we can allow you to suppress the receipt screen and create your own customized receipts. Please mail me at dhejoshi@paypal.com and I'll send you the next steps to achieve this.
