### ISSUE TITLE
Initialize merchant crash

### ISSUE THREAD

**Issue by nadia-dev** [paypal/paypal-here-sdk-ios-distribution#250]
I have a crash when I try to initialize merchant. 

Steps:
Initialize SDK -> initialize merchant -> login with test or actual merchant account -> "Accept" -> app crashes
Xcode 9.3.1, happens both on device and simulator running iOS 11

[Crash log](https://github.com/paypal/paypal-here-sdk-ios-distribution/files/2196365/PPHSDKSampleApp_2018-07-15-215516_Nadias-MacBook-Pro.crash.zip)

The app crashes when handling the redirect from the SFSafariViewController.
Workaround:
replace `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool` with `func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool` to handle redirect

**Comment by DJ92** [comment]
Hey @nadia-dev, this is mostly down to the account not being onboarded for PPH Payments. Can you please refer the onboarding guide mentioned at: (https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding) and let us know if you still have issues?

**Comment by DJ92** [comment]
Closing due to no updates. Please re-open if this is still an issue.
