### ISSUE TITLE
Cant Compile with Xcode 10 beta 5

### ISSUE THREAD

**Issue by dvalenzuela** [paypal/paypal-here-sdk-ios-distribution#259]
Followed the steps, 
1.- Download the repo. 
2.- Execute pod install
3.- Open the workspace
4.- Compile
5.- Error Message Reads
Multiple commands produce '/Users/system1/Library/Developer/Xcode/DerivedData/PPHSDKSampleApp-dmmzprimfzkkkdbdtjwqcteohaje/Build/Products/Debug-iphonesimulator/PPHSDKSampleApp.app/Info.plist':
1) That command depends on command in Target 'PPHSDKSampleApp' (project 'PPHSDKSampleApp'): script phase “[CP] Copy Pods Resources”
2) Target 'PPHSDKSampleApp' (project 'PPHSDKSampleApp') has process command with output '/Users/system1/Library/Developer/Xcode/DerivedData/PPHSDKSampleApp-dmmzprimfzkkkdbdtjwqcteohaje/Build/Products/Debug-iphonesimulator/PPHSDKSampleApp.app/Info.plist'

<img width="1512" alt="screen shot 2018-08-09 at 8 10 49 pm" src="https://user-images.githubusercontent.com/1322656/43937067-71dd3ada-9c10-11e8-8f12-473df8555316.png">

**Comment by DJ92** [comment]
Delete your pods directory and reinstall the pod dependencies using `pod install` and `pod update`. This should resolve the error mentioned in the screenshot. Please re-open the issue if this doesn't resolve it.
