### ISSUE TITLE
Deprecation of Libstdc++

### ISSUE THREAD

**Issue by dvalenzuela** [paypal/paypal-here-sdk-ios-distribution#260]
Apple deprecated libstdc++ on Xcode 10, and the image is not available any more, while looking at the linker flags it seems that this library is present thru the dylib

I believe this in Xcode 10 they actually remove it

**Comment by dvalenzuela** [comment]
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]

**Comment by DJ92** [comment]
This has been fixed with latest release. The app successfully compiles & executes on the Device and we're trying to fix the simulator runs as well in the meantime.
