### ISSUE TITLE
how to suppress  screen receipt UI when payment ??

### ISSUE THREAD

**Issue by campha10x** [paypal/paypal-here-sdk-ios-distribution#262]
how to suppress screen receipt UI when payment ?? Thank you !
![screen shot 2018-08-26 at 9 09 50 pm](https://user-images.githubusercontent.com/21209598/44629096-70e29c80-a974-11e8-90df-28f2b28b20ff.png)

**Comment by frankshieh** [comment]
Hi, I have the same request? Did any one have solution?

**Comment by ppmtscory** [comment]
Please email pph-sdk@paypal.com with your app that you're developing for as well as the business justification for needing that screen suppressed.  Somebody will reply with some terms that you need to acknowledge before we can provide the snippet to suppress that screen.
