### ISSUE TITLE
Please fix for Xcode 10

### ISSUE THREAD

**Issue by StorminGorman** [paypal/paypal-here-sdk-ios-distribution#266]
libstdc++ has been removed from Xcode 10 and now our app cannot compile.  This is a critical issue/bug. @gbramwell @jeffharrell @hkc3 @djMax @sozel

**Comment by StorminGorman** [comment]
I am able to build using the debug version but not the release

**Comment by DJ92** [comment]
We tested on a couple of devices and seems to work for both versions. There's a fix in the works too and should be out shortly.

**Comment by DJ92** [comment]
This has been fixed.
