### ISSUE TITLE
Issue refund with only PayPalId

### ISSUE THREAD

**Issue by thwaiteschris** [paypal/paypal-here-sdk-ios-distribution#270]
Hi There,
I need to be able to issue a refund, but I do not have all the info required to use the createRefundTransaction call. I have the PayPalId.

So I need to get the invoice from the server, so I can interrogate it to get the transactionNumber, PaymentMathod, and invoiceAmount.

Using the old SDK, I was able to do this:

PPHInvoiceItemContext* context = [[PPHInvoiceItemContext alloc] init];
        [PPHInvoice downloadInvoiceForInvoiceId:self.refundInvoiceId context:context completionHandler:^(PPHInvoice *invoice, PPHError *error){
            if(error !=nil){
                // error handling code here
            } else{
                // get the inf I need from the invoice
                self.refundAmount = invoice.totalAmount;
                // etc, etc
               // now actually issue the refund with the info I got from the invoice. 
            }
        }];

But I can't see how to get an invoice from the server with the new SDK.
I can see PPRetailInvoice.getDetails which supposedly gets the invoice details from the server based on the PayPalId. But I can't see any way to set the PayPalId in the PPRetailInvoice object, since it is readonly.

SO, is there any sample code out there which can show me how to use the latest SDK to get an invoice from the server based on its PayPalID.

Thanks,
    Chris

**Comment by DJ92** [comment]
Hey Chris,

Sorry about the delay in my response. You can use our new refund method using the latest SDK which does not require all the info as it did in the past. You only need the invoiceID. 

Please refer the sampleObjC App at: https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/SampleAppObjC/PPHSDKSampleApp/PaymentCompletedViewController.m#L54 

Let us know if you have any questions.

**Comment by thwaiteschris** [comment]
Hi There,

Thanks for the response.

I think I must be missing something though, since I've looked at the sample app, and the line you've linked to also needs the original TransactionNumber, PaymentType, and Amount.

I can create a sample app to issue refunds when I have all this info, no problem.

Unfortunately, in my real-world app, I do not have all this information. All I have is the InvoiceID (PayPalId).

So from the InvoiceID, how can I get the TransactionNumber, PaymentType, and Amount for the invoice that I'm refunding?

Thanks,
    Chris

**Comment by thwaiteschris** [comment]
I'm using a work-around to collect more invoice data during the payment stage for now. But I find it hard to believe I can't fetch the invoice from the InvoiceId using the SDK.
