### ISSUE TITLE
Listener for CardReader connect/disconnect

### ISSUE THREAD

**Issue by thwaiteschris** [paypal/paypal-here-sdk-ios-distribution#271]
Hi There,

I'm struggling through porting my app from the old v1.6.x version of the PayPalHereSDK to the new 2.x version of the PayPalRetailSDK.

As far as I can see, the old watchers/listeners for CardReaders being detected/removed has been completely deprecated and not replaced.

So my question is: Just to confirm, before I start writing my own polling code to listen for readers being switched on and off, is there definitely no version of the following methods in the new SDK:

- (void)activeReaderChangedFrom:(PPHCardReaderMetadata *)previousReader to:(PPHCardReaderMetadata *)currentReader {
}

- (void)didDetectReaderDevice:(PPHCardReaderMetadata *)reader {
}

- (void)didReceiveCardReaderMetadata:(PPHCardReaderMetadata *)metadata {
}

- (void)didRemoveReader:(PPHReaderType)readerType {
}

Thanks,
    Chris

**Comment by ppmtscory** [comment]
Please check out the `PPRetailPaymentDevice` class, [here](http://paypal.github.io/paypal-here-sdk-ios-distribution/Classes/PPRetailPaymentDevice.html), for all of the connected/disconnected listeners that are available.

**Comment by thwaiteschris** [comment]
Hi There,

Thanks for the help. It looks like those listeners are exactly what I'm after. But at the risk of looking extremely stupid (I'm not an iOS developer, just winging it), I'm not sure how to implement any of them. And none of them are used in either of the sample apps.

If you could point me towards a 20 line objective-c example of any of these listeners in action, I'd really appreciate it. 

Thanks,
    Chris

**Comment by ppmtscory** [comment]
I’ll have to look and see if we have a sample, but once you have your paymentDevice connected, you’ll add it like paymentDevice.addConnectedListener

**Comment by thwaiteschris** [comment]
Thanks for the help. I can now use the disconnected listener, which was what I need.
