### ISSUE TITLE
PPRetailPaymentDevice.pendingUpdate issue

### ISSUE THREAD

**Issue by thwaiteschris** [paypal/paypal-here-sdk-ios-distribution#272]
I have a PayPalHere bluetooth card reader (M010-PROD10-V2-5, S/N: 010669725).

When I run a Total Factory Reset on the card reader and then run the SDK v2.1 Objective-C sample app, I would expect to be told that an update is required. But I am not: the PPRetailPaymentDevice.pendingUpdate property remains nil.

However, when I try to run a transaction against the sample app, the screen no longer shows the usual "Insert, Tap, or Swipe" message. Instead is shows the older version message: "Present Card". And when I attempt to complete the transaction by inserting my card, I get an error: "transaction Cancelled Unable to process payment Please remove card".

As I say: the sample app does not flag that my reader needs an update, even though it has been reset to the (2 year old at least) factory reset.

When I run the SDK v1.6.x sample app, I AM told that the reader needs an update, which goes through as expected. After the update using the older SDK, I can once again use the SDK v2.1 sample app to make and refund payments.

Is this a known issue? Are there any other ways I can interrogate whether the card reader needs an update with the v2.1 SDK? If it makes any difference, I am working with the Objective-C sample app.

Thanks,
    Chris

**Comment by ppmtscory** [comment]
Are you following the same [code](https://github.com/paypal/paypal-here-sdk-ios-distribution/blob/master/SampleAppObjC/PPHSDKSampleApp/DeviceDiscoveryViewController.m#L111) as what's used in the sample app for the update check after the reader is connected?  This is known working code.  If you still have issues, please let us know your code that handles this and we can take a look.

**Comment by thwaiteschris** [comment]
Hi There,
Thanks for the response. I'm using the code in the sample app because I'm just running the objective-c sample app with no changes at all. 
When I factory reset my card reader, the objective-c sample app for the v1.6.x sdk correctly identifies that the card reader needs to be updated. When I run the objective-c sample app from the v2.x sdk, no update (required or not) is identified. The PPRetailPaymentDevice.pendingUpdate property remains a stubborn nil.
If this is known working code, then I guess there must be something wrong/different with my card reader.
If you need more info, please let me know. Objective-c is not my forte (I'm usually a c# developer). so please explain what you might need (and where I can copy-paste it from) as if you were talking to an idiot!
Thanks,
    Chris

**Comment by ppmtscory** [comment]
Let me run some tests and get back to you.  There were some updates to the sample app recently so perhaps something broke and I’m just not aware.  Stay tuned...

**Comment by ppmtscory** [comment]
I just tested the firmware update with the EMV Chip Reader in the ObjC sample app and everything updated just fine.  As long as you're using the same code as the sample, you should be good.  With the EMV Chip reader, there's a pinhole next to the power button that you can use to reset the reader back to factory which should trigger the update within the SDK.

**Comment by thwaiteschris** [comment]
Thanks for looking into it for me, but I can categorically tell you that's not the case with my card reader. I reset the reader back to factory settings and then run up the sample app, and no update is triggered. 

I've tried this with both the swift and objective-c sample apps. Neither of which trigger an update.
Running my existing app (which uses the v1.6 SDK) an update IS triggered.

I guess there must be something unique to my own card reader. But this means I will have to stay on the 1.6 SDK.

Thanks anyway,
    Chris

**Comment by ppmtscory** [comment]
Is there anything showing in the console logs that would give any insight into what's happening?  Are there any errors or warnings thrown at all?

**Comment by nbaulesglobalsolutions** [comment]
I’m completely lost with this system and how to work the PayPal coding.

Would there be a possibility for the companies to consider automating the system? Like have us newbies focus on ads and selling the products while the experts code and align our end users? This would save a lot of time.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by thwaiteschris** [comment]
For what it's worth, the official PayPalHere app detects that the reader needs an update as well. It's just the swift and Obj-C sample apps in the latest SDK that don't.
I can't help but think that I'm screwing it up somehow, but I don't see how. Once the reader is updated, everything else in both sample apps works as expected, from initialization, through connection, through to payments and refunds...

**Comment by thwaiteschris** [comment]
Just seen the comment about the console logs. It's hard to tell since they are extremely verbose. I'll run through them and see if anything jumps out. I'll let you know. Thanks for sticking with this!

**Comment by thwaiteschris** [comment]
Here's the part of the console output that I think might be of interest. Let me know if you want/need the full console output of the connection:

2018-10-17 16:40:17.923253+0100 PPHSDKSampleApp[263:5268] DEBUG: [paymentDevice] setCardReaderToMerchant> newManifest: {"readers":["3-10669725"]}

2018-10-17 16:40:17.942590+0100 PPHSDKSampleApp[263:5268] DEBUG: [paymentDevice] setCardReaderToMerchant> Updated reader manifest: {"readers":["3-10669725"]}

2018-10-17 16:40:18.343006+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 8

2018-10-17 16:40:18.344010+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 9

2018-10-17 16:40:18.344784+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] POST https://api-m.paypal.com/v2/retail/validate-config (479ms): 422

2018-10-17 16:40:18.345505+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 10

2018-10-17 16:40:18.345956+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 13

2018-10-17 16:40:18.346389+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 15

2018-10-17 16:40:18.346925+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 16

2018-10-17 16:40:18.347361+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 17

2018-10-17 16:40:18.347770+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 19

2018-10-17 16:40:18.349348+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 21

2018-10-17 16:40:18.352493+0100 PPHSDKSampleApp[263:5268] ERROR: [paypalRest] Received error (domain: , code: UNPROCESSABLE_ENTITY, message: The requested action cannot be performed, and may require interaction with APIs or processes outside of the current request, debugId: 4657ef5cf0287, details: undefined There is no configuration for this input combination)

2018-10-17 16:40:18.380145+0100 PPHSDKSampleApp[263:5268] DEBUG: [paypalRest] PayPalREST.request 23

2018-10-17 16:40:18.381652+0100 PPHSDKSampleApp[263:5268] ERROR: [sdk.deviceBuilder] firmwareUpdateRequestVersionInfoError {

  "url": "https://api-m.paypal.com/v2/retail/validate-config",

  "err": {

    "code": "UNPROCESSABLE_ENTITY",

    "debugId": "4657ef5cf0287",

    "developerMessage": "domain: , code: UNPROCESSABLE_ENTITY, message: The requested action cannot be performed, and may require interaction with APIs or processes outside of the current request, debugId: 4657ef5cf0287, details: undefined There is no configuration for this input combination",

    "details": [

      {

        "issue": "There is no configuration for this input combination",

        "location": "body"

      }

    ],

    "line": 47335,

    "column": 38,

    "sourceURL": "manticore://root"

  },

  "response": "{\"headers\":{\"X-Cnection\":\"close\",\"Content-Type\":\"application/json\",\"Server\":\"Apache\",\"Pragma\":\"no-cache\",\"Set-Cookie\":\"X-PP-SILOVER=name%3DLIVE6.API.1%26silo_version%3D880%26app%3Dapiplatformproxyserv%26TIME%3D3780626267%26HTTP_X_PP_AZ_LOCATOR%3Ddcg13.slc; Expires=Wed, 17 Oct 2018 16:10:18 GMT; domain=.paypal.com; path=/; Secure; HttpOnly, X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT\",\"Content-Length\":\"300\",\"Date\":\"Wed, 17 Oct 2018 15:40:18 GMT\",\"Vary\":\"Authorization\",\"Paypal-Debug-Id\":\"4657ef5cf0287, 4657ef5cf0287\",\"Cache-Control\":\"max-age=0, no-cache, no-store, must-revalidate\",\"Connection\":\"close\"},\"statusCode\":422,\"body\":{\"message\":\"The requested action cannot be performed, and may require interaction with APIs or processes outside of the current request\",\"debug_id\":\"4657ef5cf0287\",\"details\":[{\"issue\":\"There is no configuration for this input combination\",\"location\":\"body\"}],\"name\":\"UNPROCESSABLE_ENTITY\",\"links\":[]}}"

}

2018-10-17 16:40:18.407851+0100 PPHSDKSampleApp[263:5268] DEBUG: [paymentDevice.miura.connectionFlow] Received firmware update response for this.device: {"id":"PayPal 725","manufacturer":"MIURA","model":3,"serialNumber":"10669725"}

2018-10-17 16:40:18.408253+0100 PPHSDKSampleApp[263:5268] ERROR: [paymentDevice.miura.connectionFlow] Unable to retrieve firmware update information for PayPal 725, manufacturer=MIURA, model=3. Error: Error: The requested action cannot be performed, and may require interaction with APIs or processes outside of the current request

2018-10-17 16:40:18.428674+0100 PPHSDKSampleApp[263:5268] WARN: [paymentDevice.miura.connectionFlow] {

"message": "The requested action cannot be performed, and may require interaction with APIs or processes outside of the current request",

"debug_id": "4657ef5cf0287",

"details": [

{

"issue": "There is no configuration for this input combination",

"location": "body"

}

],

"name": "UNPROCESSABLE_ENTITY",

"links": []

}

**Comment by ppmtscory** [comment]
That's exactly what I needed.  Are you using the older white EMV reader or the new black one with the screen?

**Comment by thwaiteschris** [comment]
It's black with a screen. Bought about 18 months ago in the UK.

**Comment by ppmtscory** [comment]
Ok, thank you.  I will look up those logs and get back to you with my findings.

**Comment by ppmtscory** [comment]
One last question, are you setting the environment in the app to sandbox or Live when you are doing this?

**Comment by thwaiteschris** [comment]
Sorry for the delay. I'm in the Live environment.

**Comment by ppmtscory** [comment]
What are you setting for the `SdkCredential` fields?  It looks like something is getting set incorrectly there.  These would be set during the merchant initialization.

**Comment by thwaiteschris** [comment]
I'm setting the AccessToken and RefreshUrl that I retrieve from my own Auth Server, and the Environment= "LIVE".

I can send you an actual token and refreshUrl if that would be useful. But It'll only last for 8 hours...

I was assuming that the merchant initialization was working OK, since I can make payments and refunds, and they all show up properly when I view my account at paypal.com. And the PPRetailError property for the completionHandler of initializeMerchantWithCredentials is returning nil.

**Comment by ppmtscory** [comment]
No need to send anything, the issue is with your environment.  You'll need to set it to all lowercase, `live` instead of all caps.  Once you do that, then the SDK will pick up the environment correctly and the reader update repository will be selected correctly as well.

**Comment by ppmtscory** [comment]
The correct value for sandbox is all lowercase `sandbox` as well.

**Comment by thwaiteschris** [comment]
OK, I'll give that a try and let you know in 5. Thanks.

**Comment by thwaiteschris** [comment]
Ha!! That worked! Thanks so much for looking into it. Sorry to have wasted your time!

**Comment by ppmtscory** [comment]
Definitely not a waste.  We should be able to handle this situation better on our end to not have this issue come up for our developers.  I will talk to the right folks to try to prevent this going forward.
