### ISSUE TITLE
Application crashes while user accepts transaction (using all currencies except USD)

### ISSUE THREAD

**Issue by kidasov** [paypal/paypal-here-sdk-ios-distribution#274]
**Device**: IPad4 (IOS 10)
**CardReader**: Paypal CardReader
**Application**: Sample App.

There is a problem in sample app when user can not make transaction because of application crash.
It happens when invoice currency is not USD.  For example JPY, CZK etc. But all invoices that were initialized with USD currency worked correctly.

```
 var invoice: PPRetailInvoice?
invoice = PPRetailInvoice.init(currencyCode: "JPY")
invoice?.addItem("Test product" quantity: 1, unitPrice: 1000, itemId: 123, detailId: nil)
```
When I tried to accept transaction application crash happened.
`PPHSDKSampleApp[3585:1749444] *** Terminating app due to uncaught exception 'PPManticoreNativeInterfaceException', reason: 'Manticore engine encountered an error.
Message: undefined is not an object (evaluating 'Currency.getCurrency(currency).toCents')`

I didn't found any information in internet for this error message. All currencies were added to the PayPal sandbox account (marked primary).
Any help will be highly appreciated.

**Comment by DJ92** [comment]
Hey @kidasov,

Unfortunately, our SDK is only certified and supported in the US, UK and AU for now. Please find more info at: https://developer.paypal.com/docs/integration/paypal-here/merchant-onboarding/signing-up/#

Thanks!
