### ISSUE TITLE
This credit card cannot be processed by PayPal

### ISSUE THREAD

**Issue by kidasov** [paypal/paypal-here-sdk-ios-distribution#281]
**Device**: IPad4 (IOS 10)
**CardReader**: Paypal CardReader
**Application**: Sample App.

Transaction was declined during the payment in live mode. In test mode everything worked fine. 
Once I tried to accept transaction in live mode I got this error
`{"correlationId":"fcf989bd14f96","errorCode":580031,"errorType":"pay/bad_card","message":"Please try another card","developerMessage":"This credit card cannot be processed by PayPal","authCode":"","responseCode":""}`

Paypal CardReader showed this message ("_**please contact your card issuer**_"). Live account was registered in USA, card issuer is from another country.
Any help would be greatly appreciated.

**Comment by DJ92** [comment]
Hey @kidasov ,

It seems like a Risk Decline from our platform based on the information you provided. You should have it working with a different live card. `ERROR_DCC_CC_RISK_SCORE_EXCEEDED`

**Comment by kidasov** [comment]
It seems that none of the cards worked. Could you please give me more info on what a Risk Decline may be caused by?  Can the error be related to the fact that the cards are issued in the coutry not supported by PayPal here?

**Comment by DJ92** [comment]
Please connect with me at dhejosh@paypal.com to enable a flag for outside the US testing.
