### ISSUE TITLE
Do not show maskedEmail on payment complete screen

### ISSUE THREAD

**Issue by kidasov** [paypal/paypal-here-sdk-ios-distribution#282]
**Device**: IPad4 (IOS 10)
**CardReader**: Paypal CardReader
**Application**: Sample App.

After successful transaction, when user already bought stuff, I need to dismiss maskedEmail field on payment complete screen. Is there a way to enter email every time manually if user bought something?
Any help would be appreciated.

**Comment by DJ92** [comment]
Hey @kidasov , there's nothing specifically implemented to dismiss it but you can provision your own receipts if you'd like. You can reach out to me at dhejoshi@paypal.com for specific details on that.
