### ISSUE TITLE
deviceManager.scanAndAutoConnect callback never fired

### ISSUE THREAD

**Issue by kidasov** [paypal/paypal-here-sdk-ios-distribution#285]
I have this code. But scanAndAutoConnect callback never fired.
```
func autoConnectLastReader() {
        let deviceManager = PayPalRetailSDK.deviceManager();
        if let readerName = deviceManager?.getLastActiveBluetoothReader() {
            deviceManager?.scanAndAutoConnect(toBluetoothReader: readerName, callback: { (error, cardReader) in
                if(error != nil) {
                   
                }
                if(cardReader?.isConnected())! {
                    // Ready to accept payments
                }
            })
        } else {
            // Find and connect
        }
    }
```
Any help will be appreciated.

**Comment by DJ92** [comment]
Hi @kidasov ,

The scanAndAutoConnect() method returns a DeviceConnection callback and therefore, needs to be handled inside a connection() method. Here's a snippet for that behavioir ->

```@IBAction func autoConnectReader(_ sender: UIButton) {
        autoConnectActivityIndicator.startAnimating()
        autoConnectReader.isHidden = true
        let lastActiveReader = deviceManager?.getLastActiveBluetoothReader()
        deviceManager?.scanAndAutoConnect(toBluetoothReader: lastActiveReader, callback: { (error, paymentDevice) in
            self.autoConnectActivityIndicator.stopAnimating()
            self.autoConnectReader.isHidden = false
            if error != nil {
                print("Error in connecting with bluetooth reader via Auto Connect: " + (error?.developerMessage)!)
                self.activeReaderLbl.text = "Error: \(error?.message ?? "No Last Reader")"
            } else {
                if (paymentDevice?.isConnected())! {
                    self.checkForReaderUpdate(reader: paymentDevice)
                    print("Connected automatically with device.")
                }
            }
        })
    }```

**Comment by kidasov** [comment]
@DJ92 Thank you for your response. It works if I run native application. But we use this library in react-native app, so my problem is that all other methods work fine, but this method is never executed.
 `deviceManager?.scanAndAutoConnect(toBluetoothReader: lastActiveReader, callback: { (error, paymentDevice) in
            print("In scanAndAutoConnect callback we are")
        })`

**Comment by DJ92** [comment]
Hey @kidasov,

Unfortunately, we don't have an official support for react-native apps just yet. I'd have to defer back to you for correctly wrapping the SDK inside the app and I can only help you with the functionality/feature gaps.
Thanks!

**Comment by pnemere** [comment]
Hi @DJ92 - on a related note:

What happens if you call scanAndAutoConnect and your app is sitting there waiting for a callback... which maybe doesn't happen.

Meanwhile a user clicks a connect button on your app, which calls searchAndConnect (and the window pops up), user clicks on a device and connection is made that way.

Would the scanAndAutoConnect callback be called after this point? Is it forever sitting there waiting? or is the callback cancelled if you use searchAndConnect?

Thanks!
