### ISSUE TITLE
Processing window can't be closed

### ISSUE THREAD

**Issue by anton8900** [paypal/paypal-here-sdk-ios-distribution#287]
When poor connection or connection between reader and android device somehow drops down sometimes occures you library holding my app in "Processing" forever. Please watch this video:

https://drive.google.com/drive/u/0/folders/1_8NQdpLEhcQkphuDoKDIgOqA_MVoHoXT

In this case it should cancel processing after some timeout
Or you need to add cancel button or handle back button

**Comment by DJ92** [comment]
I looked at the videos @anton8900 and I see that the video where processing is stuck, the reader is actually disconnected. Not sure, what your code is but have you enabled background options in the Manifest for your app. By default, the connection timeout is 3 mins on that device and no dropoffs if it's always being charged. 

Also, the NFC use case, I'll need more info on what kind of top-up use case are you trying to establish. Please send me your responses at dhejoshi@paypal.com.
