### ISSUE TITLE
App Crash - PPManticoreNativeInterfaceException

### ISSUE THREAD

**Issue by asa47** [paypal/paypal-here-sdk-ios-distribution#292]
Hello,

We received some crash reports from our customers, could you please help us investigating the issue?

**Location**: Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK
**Exception**: PPManticoreNativeInterfaceException 
**Message**: 

> Manticore engine encountered an error. Message: null is not an object (evaluating '_Merchant2.default.active.cardSettings') JS Stack: isInvoiceAmountBelowAllowedMinimum@manticore://root:21758:54 handleCardPresent@manticore://root:18658:58 manticore://root:19262:56 emit@manticore://root:34113:22 emit@manticore://root:72762:68 manticore://root:49492:21 manticore://root:51914:15 _handleNextResponse@manticore://root:52748:31 _responseHandler@manticore://root:52695:29 manticore://root:52459:29 emit@manticore://root:34105:21 manticore://root:49793:18

Please let us know.

Kind Regards.

**Comment by ppmtscory** [comment]
The `isInvoiceAmountBelowAllowedMinimum` piece suggests that you're submitting a payment with an amount too low.  The minimum is 1 in each currency denomination - 1 USD, 1 GBP, & 1 AUD.
