### ISSUE TITLE
Advertising Identifier, submitting to App Store

### ISSUE THREAD

**Issue by uddinr** [paypal/paypal-here-sdk-ios-distribution#295]
we are attempting to submit our app to the app store, however, it seems that this SDK is using the Advertising Identifier, can you please explain why this is being used? can this please be removed as it is holding up our release process.

i am using the following command to identify which framework is using the advertising identifier:
https://stackoverflow.com/questions/31779092/how-do-i-check-where-my-app-is-using-idfa

grep -lr "advertisingIdentifier" * | grep -v .svn | grep -v .md

This command returns the following result:

Pods/PayPalHereSDKv2/RSDK/Release/PayPalRetailSDK.framework/PayPalRetailSDK

i am using pod 'PayPalHereSDKv2/Release'

**Comment by utkarshss** [comment]
We're facing the same issue, using latest release  2.1.0219063010.

**Comment by w-star** [comment]
has anyone been able to submit app to app store with latest PayPal Here SDK using the advertising identifier? 

If yes, what did you select in the following list?
- Serve advertisements within the app
- Attribute this app installation to a previously served advertisement
- Attribute an action taken within this app to a previously served advertisement

**Comment by uddinr** [comment]
yes we have managed to submit to app store by selecting the third option:

- Attribute an action taken within this app to a previously served advertisement

I think some form of explanation why this needs to be used and guidance on what option should be selected needs to be added to the docs
