### ISSUE TITLE
'Insufficient Funds' prompt shown incorrectly

### ISSUE THREAD

**Issue by gmann1** [paypal/paypal-here-sdk-ios-distribution#296]
SDK v2.1.0219018012

Customer reported that 'Insufficient Funds' was shown when they started a new transaction (no card had been inserted yet).  

This occurred only once that we know about.

Customer was able to hit 'ok' and start another transaction just fine.

**Comment by ppmtscory** [comment]
Have not heard of this happening in later versions from other communication channels but if I'm incorrect, please do let me know a recent date/time and I can have a look.
