### ISSUE TITLE
Release vs Debug

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#300]
So I'm using the pod called: `pod 'PayPalHereSDKv2'` however the Readme mentions release builds are in the pod called: `pod 'PayPalHereSDKv2/Release'`. Should I use the release build? What functional differences are there between debug and release?

Is it purely just a matter of log level differences or similar? The debug pod does a lot of logging to the xcode console, I haven't tried the release build.

Are they always in sync? I have seen some changes checked into /Release but not /Debug so I'm a little confused (see https://github.com/paypal/paypal-here-sdk-ios-distribution/pull/293)

My app is not distributed on the App store, but is installed as an enterprise app via Cisco Meraki, so I'm perhaps less restricted than a normal AppStore releaser.

**Comment by ppmtscory** [comment]
Debug and Release should be in sync and yes the difference between them is logging.  You should not be using Debug in your production apps.
