### ISSUE TITLE
M010 AutoConnect - How many times can this be called? Should I call it whenever a device disconnects?

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#303]
With an M010 device connected to the sample app, if the device goes to sleep for any reason/disconnects from bluetooth/reboots etc, once it's disconnected from bluetooth, should my client application automatically call `scanAndAutoConnect()` to the last active reader?

Does calling it once set it as a "state" and it's meant to auto connect to the last active reader automatically whenever a disconnection occurs? (because it doesn't seem to be doing this!)

Is it safe to auto-reconnect automatically? Can some transaction that was active say 10 minutes ago suddenly continue on at this point?

**Comment by gmann1** [comment]
@DJ92 @ppmtscory as you know I've had issues with this as well. Are there plans to make auto connect from the SDK work the same way as the PayPal here app? The app has additional logic to get it to work with different states. It has been difficult to get it to work the same way using auto connect from the SDK.

I think everyone would prefer to have a listener that auto connects and publishes device state (searching, connected, not found, disconnected, etc) (the same way the PayPalHere app works) in lieu of having to connect manually and shown a list of eligible devices (this could always be a fallback) and the current implementation of AutoConnect from the SDK seems too complex/error prone. I'd settle for a guide written in swift ;)

**Comment by ppmtscory** [comment]
Hmm.. I think I may not quite understand the ask here.  You have to call `scanAndAutoConnect` explicitly as there's no way to have the SDK automatically try to connect if a disconnect happens.  This method is simply provided as a convenience if you're going to be using the same reader every time.  If you're going to be switching readers around, then it's probably not the best method to use for the main connection method.  You can pair it with the reader disconnect listeners to auto connect back to the same reader if you want.

If I'm misunderstanding the point, please do let me know.
