### ISSUE TITLE
Does the SDK cancel active transactions if a new one is attempted?

### ISSUE THREAD

**Issue by pnemere** [paypal/paypal-here-sdk-ios-distribution#304]
`PayPalHereSDKv2 version 2.1.0219063010`
I did not see any documentation specifically around this.

What happens if a transaction (TX1) is created in the usual way:
1. Create invoice...
2. `PayPalRetailSDK.transactionManager()?.createTransaction`
3. tc!.setCardPresentedHandler { (cardInfo) -> Void in
4. tc!.setCompletedHandler { (error, txnRecord) -> Void in ...
5. tc!.beginPayment(options)

After this point, something goes wrong (see my other issues, eg https://github.com/paypal/paypal-here-sdk-ios-distribution/issues/302 for an example of how)...

Is this transaction now stuck waiting for something to happen? 

f I were to create a new invoice in the client app, new transaction (TX2) etc, when a device is later connected, would it perhaps resume TX1 or be processing TX2 at this point? Will it ever call back to the completedHandler of TX1 to say it has been cancelled?

**Comment by ppmtscory** [comment]
If there's something that goes wrong after the payment has started, then you should get an action back to your completionHandler with either success or failure.  At this point, if you haven't overridden the transaction context, you should be able to call beginPayment on that again if you need to.  If you've created a different invoice and subsequent transaction context, then beginPayment would use that second context.
