### ISSUE TITLE
Won't build. There's Swift in here.

### ISSUE THREAD

**Issue by 1jump2** [paypal/paypal-here-sdk-ios-distribution#312]
PaymentViewController.m 

if let err = error {
                NSLog(@"Error Code: %@", err.code);
                NSLog(@"Error Message: %@", err.message);
                NSLog(@"Debug ID: %@", err.debugId);
                return;
            } else {
                [weakSelf goToOfflinePaymentCompletedViewController];
            }
Change to:

if (error) {
                NSLog(@"Error Code: %@", error.code);
                NSLog(@"Error Message: %@", error.message);
                NSLog(@"Debug ID: %@", error.debugId);
                return;
            } else {
                [weakSelf goToOfflinePaymentCompletedViewController];
            }

**Comment by ppmtscory** [comment]
Apologies for that, we'll get it fixed in the sample and then I'll close this out.

**Comment by ppmtscory** [comment]
This has since been fixed.
