### ISSUE TITLE
swift sample app wont build in xcode 10

### ISSUE THREAD

**Issue by chrisjfunk** [paypal/paypal-here-sdk-ios-distribution#313]
Include of non-modular header inside framework module 'PayPalRetailSDK': '/Users/.../paypal-here-sdk-ios-distribution/SampleApp/Pods/PPRetailInstrumentInterface/PPRetailInstrumentInterface/PPRetailInstrumentInterface/PPRetailInstrumentationDelegate.h'

**Comment by steffanhalv** [comment]
@chrisjfunk I have this problem to. How did you solve it?
