### ISSUE TITLE
Signature view on iOS13

### ISSUE THREAD

**Issue by bgiacomelli-ebizmarts** [paypal/paypal-here-sdk-ios-distribution#316]
When we reach the Signature view and trying to sign it draws a small portion of the gesture and then starts to scroll the modal(it used to be "full screen" as far as I remember)

We have seen the same problem on other payment methods, this issue is only with XCode 11 and above.

**Comment by centerax** [comment]
@EarthyOrange Hello, do you acknowledge this problem?

**Comment by ppmtscory** [comment]
This issue was due to changes in modal displays with iOS 13 and has been resolved with a recent release.  If you update your SDK version, you'll see this fixed.

**Comment by centerax** [comment]
Hi Cory,

To which release specifically? There is no recent release on the
repository, just tags.

Thanks.
Pablo Benitez
CTO
https://magento.com/resources/better-store-experience-increases-both-loyalty-and-sales

**Comment by ppmtscory** [comment]
The latest release on CocoaPods and also framework within Github is `2.1.0319351000` and that will contain the fix you're looking for.
