### ISSUE TITLE
[Sandbox] Payment declines after entering Pin on the PayPal HERE device

### ISSUE THREAD

**Issue by chauhanmahesh** [paypal/paypal-here-sdk-ios-distribution#318]
Facing some weird issue in sandbox environment. Everytime when I try to do the payment more than $100 AUD, device asks for a PIN (which makes sense). However, after entering correct PIN it fails every single time.
Haven't seen any issue when testing with smaller amounts.

Also observed that when I tried to test bigger amount with a test credit card it works (In that case SDK asks for signature and not PIN).

So may be the issue is with a Pin logic. Can someone please help with this issue.

**Comment by chauhanmahesh** [comment]
Btw the logs which I can see is this

`2019-11-22 14:22:31.661563+1100 Payment[519:66373] DEBUG: [flow.baseTransactionFlow] Will not void transaction. Declined with error: {"code":"600000","domain":"retail","debugId":"c496cef3c41e5","line":65271,"column":38,"sourceURL":"manticore://root"}`

**Comment by ppmtscory** [comment]
Apologies for the delay - can you please [file a ticket](https://www.paypal-support.com/) with our technical support team and provide a more recent debug ID in your ticket so they can take a look at the error in our logs?
