### ISSUE TITLE
Possible to hide the "Processing" dialog?

### ISSUE THREAD

**Issue by mark-wade** [paypal/paypal-here-sdk-ios-distribution#322]
I am setting `options.showPromptInApp` to `false` in order to present my own UI. I also set `options.isAuthCapture` to `true` in order to present by own UI for receipt options using the Receipts UI.

However, the one thing that seems to be unavoidable is after calling `transactionContext.continue(with: card)` a "Processing" dialog appears. Is there any way to disable this so I can show a processing message in my own UI?

**Comment by ppmtscory** [comment]
Unfortunately there's not a way to disable that processing modal.  The `showPromptInApp` refers to the ready modal that says to tap/insert/swipe.
