### ISSUE TITLE
UIWebView deprecation issue

### ISSUE THREAD

**Issue by phannindra** [paypal/paypal-here-sdk-ios-distribution#326]
I have noticed that you are using AFNetworking pods which contains UIWebView which is now deprecated and as a result Apple won't be accepting the builds from April 2020. Can you update it in your project so that we can submit the builds. Attached is the screenshot that shows the version of AFNetworking used in PayPal Here sample app.

<img width="1512" alt="Screenshot 2020-03-16 at 10 55 10 AM" src="https://user-images.githubusercontent.com/13805549/76725638-d4aa0180-6774-11ea-95c8-4379bea8b3f2.png">

**Comment by ppmtscory** [comment]
This is being addresses and will hopefully be mitigated with the next SDK release.  Keep an eye on the repo for the next update.

**Comment by phannindra** [comment]
okay. Thank you

**Comment by sammcewan** [comment]
Can we get this updated please @ppmtscory?

**Comment by ppmtscory** [comment]
I'm told that it's going to be looked at in this current sprint which started this week.

**Comment by imobiling** [comment]
Our new mobile app is targeted to be in app store this month. Currently it's blocked by the same issue. Could you help speed up the fix? Do you happen to have any ETA on the fix meanwhile? Thank you very much!

**Comment by ppmtscory** [comment]
Barring any unforeseen complications with testing, the ETA for the release is this Friday the 8th.  Also, in order for these updates to happen, we had to bump the minimum iOS version to 10 so please do keep that in mind if you have any older devices.

**Comment by Ermahiho** [comment]
I'm in queue to waiting the release of new version because I have the same problem, thanks

**Comment by Dex19** [comment]
We also have the same problem, we can't get approval for app because of this...

**Comment by ppmtscory** [comment]
The latest SDK release (2.1.0320122010) happened yesterday and should fix the app submission issue.
