### ISSUE TITLE
Connect card reader via Bluetooth

### ISSUE THREAD

**Issue by maulikpat** [paypal/paypal-here-sdk-ios-distribution#330]
Hi,

I am using PayPalHereSDKv2 for iOS. In Connect card reader screen app is not able to find my card reader via Bluetooth.

![image](https://user-images.githubusercontent.com/2304770/80045891-a7f8b080-84bd-11ea-8bda-5820755d8e12.png)

It only detects the reader once I connect it to Bluetooth from the Settings app. 
The card reader is PayPal 277
![image](https://user-images.githubusercontent.com/2304770/80046042-38cf8c00-84be-11ea-8b9f-06671880fc31.png)

Is there any way to detect the reader directly via SDK and connect with it?

**Comment by ppmtscory** [comment]
That particular reader is not BLE enabled so it has to be paired in the bluetooth settings on the tablet/phone prior to being connected or found in the SDK.  The Chip & Tap reader and the Chip & Swipe reader are BLE enabled and so they are connected directly in the SDK instead of prior connection in the bluetooth settings of the device.  Those card readers can be found [here](https://us.paypal-here.com/).

**Comment by maulikpat** [comment]
@ppmtscory  I am not able to connect this reader with my iPad. I only can connect with my iPhone. in iPhone I already did forgot this device. Any help?

**Comment by maulikpat** [comment]
@ppmtscory is PPH iOS SDK supports new iPad OS (iOS 13)?

**Comment by ppmtscory** [comment]
Have you added `com.paypal.here.reader` to your supported external accessories for your iPad build?

**Comment by maulikpat** [comment]
@ppmtscory ok it was not. After adding its working fine. 
But is it mentioned in any developer guide? I didn't notice this.

**Comment by ppmtscory** [comment]
It's mentioned in the Going Live section where you're also told that if you submit your App to the Apple Store, and are using the Chip Card Reader, that you need to have that as the external accessory protocol and also fill out the MFi enrollment form.

**Comment by maulikpat** [comment]
@ppmtscory  thanks for the info. Ok, I didn't go with that section as my app won't go to Apple stores.
