### ISSUE TITLE
PPH iOS SDK Going Live : Code 7 error

### ISSUE THREAD

**Issue by maulikpat** [paypal/paypal-here-sdk-ios-distribution#335]
Hi,

I have set all Live values and I am able to get access token by `https://api.paypal.com/v1/oauth2/token`. 

But iOS SDK gives Code 7 error:
`SdkCredential *sdkCreds = [[SdkCredential alloc] initWithAccessToken:token refreshUrl:@"aURL" environment:@"live"];
        [PayPalRetailSDK initializeMerchantWithCredentials:(SdkCredential *)sdkCreds
        completionHandler:^(PPRetailError *error, PPRetailMerchant *merchant)`

Is there any settings missing?

**Comment by ppmtscory** [comment]
Do you have everything enabled on your Live side of your REST App where you get your Live client ID and secret?  There are certain fields on there that you need to submit to have enabled as you won't be able to enable those yourself.  The check boxes that you've selected for your sandbox environment do not automatically transfer over to the Live environment.  Please see [here](https://developer.paypal.com/docs/integration/paypal-here/sandbox-testing/configuring-accounts/#create-a-rest-application) for the boxes that need to be checked.  There should be a notice on the Live version of your REST App that tells you where to submit to enable the ones that you don't have access to do on your own.

**Comment by maulikpat** [comment]
@ppmtscory  I am not able to check below options for Live app
![image](https://user-images.githubusercontent.com/2304770/81874371-9b063480-9532-11ea-8e24-048c5ac70b96.png)

Is this causing the issue?

**Comment by maulikpat** [comment]
@ppmtscory  But I really don't need any of the scopes in my app. But I think it's mandatory to select any of them? What if I don't require any?

**Comment by ppmtscory** [comment]
Yes, that's causing your issue.  Even though you don't use them, the PPH SDK uses them to set up the merchant object that's included in the invoice you create for the payment.

**Comment by maulikpat** [comment]
@ppmtscory  ok thanks. So I need to send mail to PayPal with app information for this right?

**Comment by ppmtscory** [comment]
That's correct.  There should be instructions on your REST App for who to send the email to and what to include in said email.

**Comment by maulikpat** [comment]
@ppmtscory I just received approval from PayPal.
![image](https://user-images.githubusercontent.com/2304770/82613560-6b7eaa00-9b7a-11ea-9ef7-50e44b454bf3.png)

But I am still facing same issue. Error Code 7

Am I missing anything?

**Comment by ppmtscory** [comment]
Yes, you have to have all the address information too.  Name, email, and all address information. 
 Also you have to have PayPal Here checked on there which I'm sure you probably already do. https://developer.paypal.com/docs/integration/paypal-here/sandbox-testing/configuring-accounts/#create-a-rest-application

**Comment by maulikpat** [comment]
@ppmtscory These are the selections
![image](https://user-images.githubusercontent.com/2304770/82705389-6ed26e00-9c2c-11ea-8cf7-f3ab4e99c244.png)

**Comment by maulikpat** [comment]
@ppmtscory 
As mentioned here
![image](https://user-images.githubusercontent.com/2304770/82705562-b2c57300-9c2c-11ea-9491-c2c1ad562bcb.png)

I have only asked for Email scope. And PayPal has enabled that only. But as you I need all of the scopes so do I need to email again to PayPal for other attributes? But I am not using any of the attributes from PayPal in my App.

So I need to do here now?

**Comment by ppmtscory** [comment]
Yes, you'll need to go through the same process to enable the remaining scopes.  Even though your app is not using them explicitly, the PPH SDK is using them to gather merchant info.  You can put that in your request to enabled all of the scopes listed in the link I provided earlier.  Full name, email, and all address fields.

**Comment by maulikpat** [comment]
@ppmtscory  thanks I mailed paypal and they enable it now.

**Comment by maulikpat** [comment]
@ppmtscory  if I create a new App under my account, do I need to again send an email to the PayPal team to enable those scopes?

**Comment by ppmtscory** [comment]
Yes, for production you will have to email your business justification for each REST App that you create and want to use.
