### ISSUE TITLE
PPH iOS SDK : Error Code : 3

### ISSUE THREAD

**Issue by maulikpat** [paypal/paypal-here-sdk-ios-distribution#336]
I am trying to accept payment in the Live environment. 

I am trying to create transaction by
`[PayPalRetailSDK.transactionManager createTransaction:mInvoice callback:^(PPRetailError *error, PPRetailTransactionContext *context)`

Here I am getting `Nil` for `context` and below error

> Error Code: 3
Error Message: Merchant not initialized
Debug ID: (null)

Not sure what I am missing here. The same code was working for Sandbox.

**Comment by ppmtscory** [comment]
This means that your initializeMerchant call either did not happen or was not successful.
