### ISSUE TITLE
Unknown PPRetailTransactionContext setCompletedHandler error codes: 600002, 600000, 600075, 15, and others

### ISSUE THREAD

**Issue by christhwaites** [paypal/paypal-here-sdk-ios-distribution#340]
Hi There,

Our app (which has been running without problems for 3 years, taking intermittent PayPal Here card payments) is now taking more card payments than ever, and we are starting to see quite a few errors returning from  [self.tc setCompletedHandler:^(PPRetailError *error, PPRetailTransactionRecord *record)

My problem is that most of the error codes we're getting back don't exist in this error list: (https://developer.paypal.com/docs/integration/paypal-here/sdk-dev/errors/ ) and even those that are on the list don't seem to tally with what we're seeing.

Also, the error.developerMessage always seems to be (null). Is there a switch I need to activate to populate this?

Anyway, here is the list of errors we're concerned about (I'm happy to reopen each one as a separate issue/post if that would help):

error.code: **600002**
error.message: no txnAuthCode is returned
error.domain: null
(We are not ever carrying out authorizations (options.isAuthCapture = NO;))

error.code: **600075**
error.message: ""
error.domain: retail

error.code: **600000**
error.message: empty TxnId
error.domain: null

error.code: **15**
error.message: Bad EMV data
error.domain: PaymentDevice 
(anecdotally, I can recreate this every time by using chip-and-pin on a transaction below £20) 

error.code: **580031**
error.message: Please try another card
error.domain: retail 
(the error code states this is a hard decline, but my users tell me that quite often they can take successful payment simply by re-presenting the same card. Could that be correct?) 

error.code: **580022**
error.message: ""
error.domain: retail 
(the error code states this is a hard decline, but again, my users tell me that quite often they can take successful payment simply by re-presenting the same card. Could that be correct?) 

Any help with any/all of these errors would be appreciated. Currently our users just don't believe any "transaction declined" messages, and are habitually just re-presenting the same cards repeatedly. We really need to be able to tell them what to do in the event of each of these issues...

Please let me know if you need any further info, and I'll do my best to gather it.

Thanks,
    Chris

**Comment by ppmtscory** [comment]
Hello Chris - for post live support issues such as this, can you please file a ticket at https://www.paypal.com/mts and somebody can have a look?  It's likely that they'll need account specifics to look into the errors so please provide account email and date/time stamps (with timezone) for each error example.
