### ISSUE TITLE
SDK isn't listening for taps after swiping.

### ISSUE THREAD

**Issue by matt-tyler-eb** [paypal/paypal-here-sdk-ios-distribution#364]
SDK VERSION: 2.2.0020356030
### Summary
SDK isn't listening for contactless card taps after swiping the magnetic strip.

### Steps to Reproduce:

1. Ready the app for credit card use and connect with a Paypal Here Card chip & tap card reader.
2. Using a card that is chip and tap capable, SWIPE it. This will show this error to the user "Chip card detected Please insert card". That's good. You hit the OK button and it changes the message to "Ready Insert a card". At this point, it ignores any swipes or taps and only accepts chip usage.
3. This is a bug, it should be listening for taps as well during this point in the UX.

**Comment by shupaypal** [comment]
This works in the latest release, v2.3.0021161010.
