### ISSUE TITLE
Macbook pro M2: PPRetailInstrumentInterface incompatible architecture (have 'arm64', need 'x86_64')  and Library not loaded: @rpath

### ISSUE THREAD

**Issue by maulikpat** [paypal/paypal-here-sdk-ios-distribution#378]
Hello,

My app is not running on the simulator on M2 due to this run time error:

`MyApp.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')),` though it's working and running fine on intel based Macbook. It also works fine if I use the Rosetta simulator on M2.

I have tried every possible step from the internet to fix this like, pod uninstall and install, build clean & run, clear cache, delete all the simulators and create again even delete Xcode and reinstall.

Any help or suggestions, please?

Full error:

`dyld[32409]: Library not loaded: @rpath/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface
  Referenced from: <D5A32C11-DE0F-37DF-95CE-0BBD07331675> /Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PayPalRetailSDK.framework/PayPalRetailSDK
Message from debugger: Terminated due to signal 6
  Reason: tried: '/Users/user1p/Library/Developer/Xcode/DerivedData/My_App-earvxvczbovpvbfzdozmhwxgliuz/Build/Products/Debug-iphonesimulator/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PayPalRetailSDK.framework/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PayPalRetailSDK.framework/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/usr/lib/swift/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file, no dyld cache), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file), '/usr/lib/swift/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file, no dyld cache), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/user1p/Library/Developer/CoreSimulator/Devices/17086520-080E-4B11-AA41-286496A06AE1/data/Containers/Bundle/Application/DA9A1C52-D5C0-4F4F-AD2C-C0F107D79B0E/My.app/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PPRetailInstrumentInterface.framework/PPRetailInstrumentInterface' (no such file)
`

**Comment by monti-star** [comment]
Hi @maulikpat, 

Are you still facing this issue? If yes, I'm happy to work with our engineering team to provide you with an answer. 

Christina

**Comment by maulikpat** [comment]
@devchristina  hi, is there any update for this issue? I am still facing.

**Comment by devchristina** [comment]
Hi @maulikpat, apologies for the delay in my response. I've synced with the team and we have a concern with the specific SDK you're trying to utilize. 

The PayPal Here product offering has been deprecated (https://us.paypal-here.com/). We apologize that this update has not made it to this repo, I will take that as an action item to complete. 

With regards to an alternative solution, we suggest that you use https://developer.zettle.com/docs/get-started/concepts/zettle-apis-sdks.
