### ISSUE TITLE
Sending custom data.

### ISSUE THREAD

**Issue by jonathanpdiaz** [paypal/paypal-here-sdk-ios-distribution#65]
We have a few pieces of data that we would like to add to our transactions.  
With the paypal REST API, we would add it to the custom data field.  

How can we do the same with the PayPal Here SDK?

So far, I have seen the cashierID, but that doesn't cover our expectations.

Thanks,

/*! Cashier ID - Indicate the merchant's sub-user (e.g. Cashier) that is responsible for a transaction. */
@property (strong,nonatomic) NSString *cashierId;

**Comment by djMax** [comment]
Generally, it would be better to store it in your systems tied to the invoiceId or some such, because the storage in other fields is very limited (like 4k or less, of which we use a decent chunk). There's invoice note/memo which should be exposed. What are the characteristics of what you're trying to store (or if you can tell me exactly, that's good too :) )

**Comment by jonathanpdiaz** [comment]
Hi @djMax, thanks for the quick answer

The client requested us to add some fields for quick reference while reviewing the data on the Paypal site. We do have something builded as you described in our side tied to the invoiceId but the client consider that it request them an extra effort to track each transaction between both systems when they are looking for something in particular.

We want to add some minimal data, like a device Identifier and the user email that did the purchase.

Thanks,

**Comment by djMax** [comment]
User email has a real field I think - billingInfo.email. deviceIdentifier in theory does get filled out. If they want to see these values on the receipt in PayPal, custom fields won't help because they're not shown there. Let me dig and see if there's a "merchant-only" memo field you could use.

**Comment by jonathanpdiaz** [comment]
Hi @djMax, 

Here are more specifics about this case, I have marked with a red arrow the field that we want to populate on the paypal portal with transactions from paypal here sdk (red arrow): 

![paypal](https://cloud.githubusercontent.com/assets/2194027/10738540/a13c5474-7bf6-11e5-8582-631602e44108.png)

This transaction was done using the Paypal API with a vaulted credit card. The nodejs framework let us fill a custom field that its displayed on the paypal site.

Same happens when working with the paypal iOS SDK, that let you fill the property custom

PaypalPayment.h
/// Optional text, for your tracking purposes. (up to 256 characters)
@property (nonatomic, copy, readwrite) NSString *custom;

Our expectation is to know if it is possible to fill in this field on the transactions that we do with the Paypal Here SDK.

Thanks

**Comment by ppmtscory** [comment]
The custom field isn't something that's able to be populated currently, however, I'll mark this as an enhancement and we'll take it as feedback for future releases.

**Comment by jonathanpdiaz** [comment]
Hi @DJ92,
Was this fixed/enhanced or just closed?
Thanks.

**Comment by DJ92** [comment]
Hey just closed it as it's already tagged. I'll send out a comment when this has been released :)
